In [1]:
import pandas as pd

In [2]:
skimsTransitCrowding = pd.read_csv('1.String _ skimsTransitCrowding.csv.gz')

In [3]:
overloadedMode = skimsTransitCrowding[skimsTransitCrowding['capacity'] <= skimsTransitCrowding['numberOfPassengers']]

In [4]:
overloadedMode['firstTwo'] = overloadedMode['vehicleId'].str[:2]

/var/folders/z4/5gq1j4sn50b62w40lgwsthh80000gn/T/ipykernel_3401/4091636193.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  overloadedMode['firstTwo'] = overloadedMode['vehicleId'].str[:2]

In [5]:
overloadedMode[overloadedMode['firstTwo'] == 'SF']
## The 77 here is actually TRAM-DEFAULT

,vehicleId,fromStopIdx,numberOfPassengers,capacity,observations,iterations,firstTwo
3746,SF:7631636,0,22,22,1,1,SF
6241,SF:7628514,0,22,22,1,1,SF
7401,SF:7631639,1,22,22,1,1,SF
11906,SF:7631638,2,22,22,1,1,SF
12297,SF:7631633,0,22,22,1,1,SF
13535,SF:7631635,0,22,22,1,1,SF
14220,SF:7628518,0,22,22,1,1,SF
18326,SF:7631707,3,22,22,1,1,SF
18720,SF:7631636,3,22,22,1,1,SF
20773,SF:7628517,1,22,22,1,1,SF
21712,SF:7631706,1,22,22,1,1,SF
25530,SF:7628517,0,22,22,1,1,SF
26299,SF:7628565,0,22,22,1,1,SF
31089,SF:7631716,0,22,22,1,1,SF
34582,SF:7628639,0,22,22,1,1,SF
39396,SF:7628646,0,22,22,1,1,SF
40311,SF:7628514,3,22,22,1,1,SF
40422,SF:7628638,0,22,22,1,1,SF
42014,SF:7631706,0,22,22,1,1,SF
43228,SF:7628516,1,22,22,1,1,SF
43460,SF:7628508,0,22,22,1,1,SF
44534,SF:7631636,1,22,22,1,1,SF
44569,SF:7628649,0,22,22,1,1,SF
46482,SF:7628517,3,22,22,1,1,SF
47416,SF:7628523,1,22,22,1,1,SF
48580,SF:7628514,2,22,22,1,1,SF
49389,SF:7631638,1,22,22,1,1,SF
49829,SF:7631633,1,22,22,1,1,SF
51248,SF:7679460,28,79,79,1,1,SF
53245,SF:7628519,0,22,22,1,1,SF
53804,SF:7631716,1,22,22,1,1,SF
54050,SF:7631707,0,22,22,1,1,SF
56435,SF:7679456,29,79,79,1,1,SF
57184,SF:7628647,0,22,22,1,1,SF
62947,SF:7628515,0,22,22,1,1,SF
66080,SF:7631663,0,22,22,1,1,SF
67470,SF:7631666,0,22,22,1,1,SF
71264,SF:7631666,1,22,22,1,1,SF
71597,SF:7628648,1,22,22,1,1,SF
79632,SF:7679460,29,79,79,1,1,SF
81408,SF:7628520,0,22,22,1,1,SF
84096,SF:7628510,0,22,22,1,1,SF
84306,SF:7631707,1,22,22,1,1,SF
85108,SF:7631636,2,22,22,1,1,SF
86392,SF:7628648,0,22,22,1,1,SF
90087,SF:7628514,4,22,22,1,1,SF
102155,SF:7631638,0,22,22,1,1,SF

In [6]:
overloadedMode.groupby('firstTwo').count()

# it's causing more denied trips -- 37% vs 24% before, VTA caused the denied trips for both BA and Tram, how many 
# boardings we should have VTA?
# TRAM-DEFAULT is for VTA light rail??

,vehicleId,fromStopIdx,numberOfPassengers,capacity,observations,iterations
firstTwo,,,,,,
BA,70,70,70,70,70,70
SF,47,47,47,47,47,47
VT,224,224,224,224,224,224

In [7]:
events = pd.read_csv('1.events.csv.gz')

/usr/local/Cellar/jupyterlab/3.2.5/libexec/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (0,1,5,6,20,22,23,24,28,29,31,33,35,36,37,38,48,49,50,53) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [8]:
events['type'].unique()

array(['departure', 'PersonEntersVehicle', 'PathTraversal', 'ModeChoice',
       'actend', 'LeavingParkingEvent', 'PersonLeavesVehicle', 'arrival',
       'actstart', 'ReserveRideHail', 'ParkingEvent', 'PersonCost',
       'Replanning', 'ChargingPlugInEvent', 'RefuelSessionEvent',
       'ChargingPlugOutEvent'], dtype=object)

In [9]:
pathTraversal = events[events['type'] == 'PathTraversal'].dropna(how='all', axis=1)

In [10]:
pathTraversal

,vehicleType,links,numPassengers,length,primaryFuel,mode,riders,toStopIndex,fromStopIndex,seatingCapacity,...,arrivalTime,departureTime,linkTravelTime,secondaryFuel,secondaryFuelType,primaryFuelType,driver,vehicle,time,type
85480,BUS-MA,"20393,134727,134715,17955,17951,132987,17949,7...",0.0,653.352,8.088759e+06,bus,NaN,NaN,NaN,12.0,...,42.0,0.0,"10.1,10.1,10.1,10.1,10.1,10.1,10.1,10.1,10.1,1...",0.0,None,Gasoline,TransitDriverAgent-MA:5323312,MA:5323312,42.0,PathTraversal
85481,BUS-MA,"20393,134727,134715,17955,17951,132987,17949,7...",0.0,653.352,8.088759e+06,bus,NaN,NaN,NaN,12.0,...,42.0,0.0,"10.1,10.1,10.1,10.1,10.1,10.1,10.1,10.1,10.1,1...",0.0,None,Gasoline,TransitDriverAgent-MA:5348932,MA:5348932,42.0,PathTraversal
149932,BUS-MA,"20389,16787,15697,15698,35152,35151,133091",0.0,1912.970,2.368333e+07,bus,NaN,NaN,NaN,12.0,...,300.0,42.0,"29,29,29,29,29,29,0",0.0,None,Gasoline,TransitDriverAgent-MA:5348932,MA:5348932,300.0,PathTraversal
149933,BUS-MA,"20389,16787,15697,15698,35152,35151,133091",0.0,1912.970,2.368333e+07,bus,NaN,NaN,NaN,12.0,...,300.0,42.0,"29,29,29,29,29,29,0",0.0,None,Gasoline,TransitDriverAgent-MA:5323312,MA:5323312,300.0,PathTraversal
149934,BUS-MA,"133091,133087,21883,21448,133066,21450",0.0,390.593,4.835698e+06,bus,NaN,NaN,NaN,12.0,...,660.0,300.0,"16.2,16.2,16.2,16.2,16.2,-0",0.0,None,Gasoline,TransitDriverAgent-MA:5323312,MA:5323312,660.0,PathTraversal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85450236,BUS-DEFAULT,"140262,140178",0.0,19.199,3.849016e+05,bus,NaN,NaN,NaN,13.0,...,108012.0,107990.0,"119,0",0.0,None,Diesel,TransitDriverAgent-SF:7600910,SF:7600910,108012.0,PathTraversal
85450238,sharedVehicle-sharedCar,"47168,47196",0.0,4470.070,6.140057e+06,car,NaN,NaN,NaN,3.0,...,108013.0,107656.0,"254.319,357.117",0.0,None,Gasoline,6698197,3412339,108013.0,PathTraversal
85450242,sharedVehicle-sharedCar,"62754,62753,41994,81666,20621,46298,36909,3033...",0.0,12061.922,1.763686e+07,car,NaN,NaN,NaN,3.0,...,108013.0,107547.0,"273.029,111.43,65.918,65.114,40.091,0.653,10.5...",0.0,None,Gasoline,6280982,1010738,108013.0,PathTraversal
85450243,sharedVehicle-sharedCar,"29136,29137,46176,46179,29261,76242,76241,4458...",0.0,18407.699,2.675651e+07,car,NaN,NaN,NaN,3.0,...,108013.0,107220.0,"5.675,4.938,2.024,117.735,3.456,23.062,11.87,5...",0.0,None,Gasoline,4759034,2891389,108013.0,PathTraversal
85450255,conv-L1-10000-to-25000-LowTech-2019,"76122,76121",0.0,4906.137,7.081355e+06,car,NaN,NaN,NaN,3.0,...,108018.0,107835.0,"2.818,182.912",0.0,None,Gasoline,2512774,430751,108018.0,PathTraversal

In [11]:
pathTraversalInOverloaded = pathTraversal[pathTraversal['vehicle'].isin(overloadedMode['vehicleId'])]

In [12]:
events['type'].unique()

array(['departure', 'PersonEntersVehicle', 'PathTraversal', 'ModeChoice',
       'actend', 'LeavingParkingEvent', 'PersonLeavesVehicle', 'arrival',
       'actstart', 'ReserveRideHail', 'ParkingEvent', 'PersonCost',
       'Replanning', 'ChargingPlugInEvent', 'RefuelSessionEvent',
       'ChargingPlugOutEvent'], dtype=object)

In [13]:
PersonEntersVehicle

NameError: name 'PersonEntersVehicle' is not defined

In [ ]:
pathTraversalInOverloaded['firstTwoOfVehicle'] = pathTraversalInOverloaded['vehicle'].str[:2]

In [ ]:
pathTraversalInOverloadedSF = pathTraversalInOverloaded[pathTraversalInOverloaded['firstTwoOfVehicle'] == 'SF']

In [ ]:
pathTraversalInOverloadedSF['mode'].unique()

In [ ]:
transitPathTraversal = pathTraversal[(pathTraversal['mode'] == 'cable_car') 
             | (pathTraversal['mode'] == 'rail')
             | (pathTraversal['mode'] == 'tram')
             | (pathTraversal['mode'] == 'subway')
             | (pathTraversal['mode'] == 'bus')]

In [ ]:
transitPathTraversal.dropna(how='all', axis=1)

In [ ]:
transitPathTraversal = transitPathTraversal[transitPathTraversal['time'] <= 86400]

In [ ]:
transitPathTraversal['hour'] = transitPathTraversal['time'] / 3600

In [ ]:
transitPathTraversal['hour'] = transitPathTraversal['hour'].astype(int)

In [ ]:
hourlytransitPathTraversal = transitPathTraversal.groupby(['hour', 'mode']).sum()

In [ ]:
hourlytransitPathTraversal.reset_index(inplace=True)

In [ ]:
bus = hourlytransitPathTraversal[hourlytransitPathTraversal['mode'] == 'bus']
bus.reset_index(inplace=True)
bus['rate'] = bus['numPassengers']/ bus['numPassengers'].sum()
bus['rate'].plot(title='bus')

In [ ]:
cable_car = hourlytransitPathTraversal[hourlytransitPathTraversal['mode'] == 'cable_car']
cable_car.reset_index(inplace=True)
cable_car['rate'] = cable_car['numPassengers']/ cable_car['numPassengers'].sum()
cable_car['rate'].plot(title='cable_car')

In [ ]:
rail = hourlytransitPathTraversal[hourlytransitPathTraversal['mode'] == 'rail']
rail.reset_index(inplace=True)
rail['rate'] = rail['numPassengers']/ rail['numPassengers'].sum()
rail['rate'].plot(title='rail')

In [ ]:
subway = hourlytransitPathTraversal[hourlytransitPathTraversal['mode'] == 'subway']
subway.reset_index(inplace=True)
subway['rate'] = subway['numPassengers']/ subway['numPassengers'].sum()
subway['rate'].plot(title='subway')

In [ ]:
tram = hourlytransitPathTraversal[hourlytransitPathTraversal['mode'] == 'tram']
tram.reset_index(inplace=True)
tram['rate'] = tram['numPassengers']/ tram['numPassengers'].sum()
tram['rate'].plot(title='tram')

In [ ]:
transitPathTraversal.groupby('mode').sum().to_csv('out/transitModesShare.csv')

In [ ]:
df = transitPathTraversal.groupby('mode').sum()[['numPassengers']]

In [ ]:
plot = df.plot.pie(y='numPassengers', figsize=(15, 25), autopct='%1.1f%%')