In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [29]:
# Preparing for import

In [40]:
# Comment or uncomment
#geo = ['SF', 'cordon']
geo = ['cordon']
sce = ['baseline', 'flat', 'income-based']
metrics = ['vmt_mode', 'vmt_mode_av', 'vht_mode', 'vht_mode_av', 'speed_mode', 'trip_count']

In [41]:
list_tables = []
list_df = []
for i in metrics:
    for j in sce:
        for k in geo:
            var = f'{i}_{j}_{k}.csv'
            df = pd.read_csv(var)
            df['geo'] = k
            df['scenario'] = j
            list_tables.append(var)
            list_df.append(df)

In [42]:
list_tables

['vmt_mode_baseline_cordon.csv',
 'vmt_mode_flat_cordon.csv',
 'vmt_mode_income-based_cordon.csv',
 'vmt_mode_av_baseline_cordon.csv',
 'vmt_mode_av_flat_cordon.csv',
 'vmt_mode_av_income-based_cordon.csv',
 'vht_mode_baseline_cordon.csv',
 'vht_mode_flat_cordon.csv',
 'vht_mode_income-based_cordon.csv',
 'vht_mode_av_baseline_cordon.csv',
 'vht_mode_av_flat_cordon.csv',
 'vht_mode_av_income-based_cordon.csv',
 'speed_mode_baseline_cordon.csv',
 'speed_mode_flat_cordon.csv',
 'speed_mode_income-based_cordon.csv',
 'trip_count_baseline_cordon.csv',
 'trip_count_flat_cordon.csv',
 'trip_count_income-based_cordon.csv']

In [50]:
# Calculate mode shares
grouped_sum_15 = list_df[15]['count'].sum()
grouped_sum_16 = list_df[16]['count'].sum()
grouped_sum_17 = list_df[17]['count'].sum()

list_df[15]['Share'] = list_df[15]['count'] / grouped_sum_15
list_df[16]['Share'] = list_df[16]['count'] / grouped_sum_16
list_df[17]['Share'] = list_df[17]['count'] / grouped_sum_17

# Calculate difference with respect to baseline
list_df[15]['Diff wrt baseline'] = (list_df[15]['count'] - list_df[15]['count'])
list_df[16]['Diff wrt baseline'] = (list_df[16]['count'] - list_df[15]['count'])/list_df[15]['count']
list_df[17]['Diff wrt baseline'] = (list_df[17]['count'] - list_df[15]['count'])/list_df[15]['count']

In [51]:
list_df[15]['Share'].sum()

1.0

In [52]:
trip_count = pd.concat([list_df[15], list_df[16], list_df[17]])
trip_count

,legMode,count,geo,scenario,Share,Diff wrt baseline
0,bike,40070,cordon,baseline,1.580576e-02,0.000000
1,bike_transit,1,cordon,baseline,3.944537e-07,0.000000
2,car,1198829,cordon,baseline,4.728825e-01,0.000000
3,car_hov2,240739,cordon,baseline,9.496038e-02,0.000000
4,car_hov3,172830,cordon,baseline,6.817343e-02,0.000000
5,drive_transit,1847,cordon,baseline,7.285559e-04,0.000000
6,hov2_teleportation,212053,cordon,baseline,8.364508e-02,0.000000
7,hov3_teleportation,189646,cordon,baseline,7.480656e-02,0.000000
8,ride_hail,39397,cordon,baseline,1.554029e-02,0.000000
9,ride_hail_pooled,13971,cordon,baseline,5.510912e-03,0.000000
10,walk,226051,cordon,baseline,8.916665e-02,0.000000
11,walk_transit,199718,cordon,baseline,7.877950e-02,0.000000
0,bike,39449,cordon,flat,1.561269e-02,-0.015498
1,bike_transit,1,cordon,flat,3.957691e-07,0.000000
2,car,1191985,cordon,flat,4.717508e-01,-0.005709
3,car_hov2,239669,cordon,flat,9.485358e-02,-0.004445
4,car_hov3,172178,cordon,flat,6.814273e-02,-0.003772
5,drive_transit,1894,cordon,flat,7.495866e-04,0.025447
6,hov2_teleportation,211880,cordon,flat,8.385555e-02,-0.000816
7,hov3_teleportation,189105,cordon,flat,7.484191e-02,-0.002853
8,ride_hail,39601,cordon,flat,1.567285e-02,0.005178
9,ride_hail_pooled,13791,cordon,flat,5.458051e-03,-0.012884
10,walk,227685,cordon,flat,9.011068e-02,0.007228
11,walk_transit,199488,cordon,flat,7.895118e-02,-0.001152
0,bike,39901,cordon,income-based,1.578851e-02,-0.004218
1,bike_transit,1,cordon,income-based,3.956922e-07,0.000000
2,car,1192639,cordon,income-based,4.719179e-01,-0.005163
3,car_hov2,240931,cordon,income-based,9.533451e-02,0.000798
4,car_hov3,172160,cordon,income-based,6.812237e-02,-0.003877
5,drive_transit,1882,cordon,income-based,7.446927e-04,0.018950
6,hov2_teleportation,210836,cordon,income-based,8.342616e-02,-0.005739
7,hov3_teleportation,189019,cordon,income-based,7.479334e-02,-0.003306
8,ride_hail,39294,cordon,income-based,1.554833e-02,-0.002614
9,ride_hail_pooled,13961,cordon,income-based,5.524259e-03,-0.000716
10,walk,226568,cordon,income-based,8.965119e-02,0.002287
11,walk_transit,200025,cordon,income-based,7.914833e-02,0.001537

In [55]:
# VMT by mode
# Calculate difference with respect to baseline
list_df[0]['Diff wrt baseline'] = (list_df[0]['length'] - list_df[0]['length'])
list_df[1]['Diff wrt baseline'] = (list_df[1]['length'] - list_df[0]['length'])/list_df[0]['length']
list_df[2]['Diff wrt baseline'] = (list_df[2]['length'] - list_df[0]['length'])/list_df[0]['length']

In [56]:
vmt_mode= pd.concat([list_df[0], list_df[1], list_df[2]])
vmt_mode

               mode        length     geo      scenario  Diff wrt baseline
0              bike  2.224894e+07  cordon      baseline           0.000000
1               bus  3.097541e+07  cordon      baseline           0.000000
2         bus_empty  2.876143e+07  cordon      baseline           0.000000
3         cable_car  1.021272e+06  cordon      baseline           0.000000
4   cable_car_empty  1.106097e+06  cordon      baseline           0.000000
..              ...           ...     ...           ...                ...
18           subway  7.771091e+06  cordon  income-based          -0.001229
19     subway_empty  3.327341e+05  cordon  income-based           0.029590
20             tram  5.922167e+06  cordon  income-based          -0.000419
21       tram_empty  2.954800e+06  cordon  income-based           0.000841
22             walk  2.058524e+08  cordon  income-based           0.008216

[69 rows x 5 columns]

In [58]:
vmt_mode.to_csv('vmt_mode_export.csv')