In [1]:
import os
import os.path as op
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
%matplotlib inline
import seaborn as sns
sns.set_theme(style="darkgrid", color_codes=True)
sns.set(font_scale=1.35, style="ticks") #set styling preferences
import statsmodels.api as sm
from scipy import stats
import math
from math import pi
from pandas.api.types import is_string_dtype
from pandas.api.types import is_numeric_dtype
from scipy.spatial.distance import cdist
from scipy.cluster.vq import kmeans2,vq, whiten

In [2]:
# Show all columns and rows
pd.options.display.max_columns = None
pd.options.display.max_rows = None

#### Baseline

In [3]:
%%time
baseline2018 = "https://beam-core-act.s3.amazonaws.com/deepDive/CleanData/SanFrancisco/Baseline/"
sfbase = pd.read_csv(baseline2018 + 'sf_2018_base_8_22_22.csv')

<timed exec>:2: DtypeWarning: Columns (42) have mixed types. Specify dtype option on import or set low_memory=False.

CPU times: total: 1min 10s
Wall time: 3min 25s

In [4]:
# Showing the entire number in dataframe
pd.set_option('float_format', '{:f}'.format)

In [5]:
#describe = sfbase.describe()

In [6]:
#describe.to_csv('C:/Shared-Work/Data/CleanData/ASIM_BEAM_Merged/describe.csv')

#### Ridehail Price-Fleetsize Scenarios

In [7]:
%%time
rh_price_path = "https://beam-core-act.s3.amazonaws.com/deepDive/CleanData/SanFrancisco/Ridehail_Price_Fleetsize/"
sf_rh_price_2p5 = pd.read_csv(rh_price_path + 'sf_2018_rh_price_2p5_flsz_0p125.csv.csv')
sf_rh_price_1p5 = pd.read_csv(rh_price_path + 'sf_2018_rh_price_1p5_flsz_0p125.csv.csv')

<timed exec>:2: DtypeWarning: Columns (43) have mixed types. Specify dtype option on import or set low_memory=False.

CPU times: total: 2min 30s
Wall time: 7min 9s

In [8]:
sfbase.shape

(2468267, 257)

In [9]:
sf_rh_price_2p5.shape

(2468083, 258)

In [10]:
sf_rh_price_1p5.shape

(2468142, 258)

In [12]:
#sf_rh_flsz_175 = sf_rh_flsz_175.drop(sf_rh_flsz_175.columns[245:625], axis=1)

In [13]:
#sf_rh_flsz_175 = sf_rh_flsz_175.drop(sf_rh_flsz_175.columns[235:245], axis=1)

In [14]:
#sf_rh_flsz_175 = sf_rh_flsz_175.drop(sf_rh_flsz_175.columns[233:235], axis=1)

In [11]:
frames = [sf_rh_price_2p5, sf_rh_price_1p5, sfbase]
sf_stacked = pd.concat(frames)

In [12]:
sf_stacked = sf_stacked.drop(['BlockGroupEnd','BlockGroupStart','has_school_kid','has_preschool_kid','has_retiree','has_non_worker','adult','hispanic','relate',
                             'pstudent','pemploy','ptype','p_hispanic','age_16_p','age_16_to_19','work_zone_id',
                             'race_id','school_zone_id','person_age','MAR','hours','hispanic.1','student',
                             'worker','stop_frequency','composition','tdd','number_of_participants','tour_type_count',
                             'tour_type_num','tour_num','tour_count', 'outbound', 'trip_num','num_under16_not_at_school',
                             'family','non_family','num_young_adults','num_college_age','num_children_16_to_17',
                              'num_children_5_to_15','num_young_children'], axis=1)

In [13]:
sf_stacked = sf_stacked.drop(['vehicleIds_estimate','destination_x','origin_x','depart',
                             'origin_y', 'destination_y','parent_tour_id','atwork_subtour_frequency','household_id_y',
                              'TAZ_x','home_x','home_y','male','female', 'has_driving_kid','has_full_time','has_part_time',
                              'has_university','student_is_employed', 'nonstudent_to_school', 'is_student','is_gradeschool',
                              'is_gradeschool','is_highschool','is_university','school_segment','is_worker','home_taz',  
                             'school_taz','distance_to_school','roundtrip_auto_time_to_school','workplace_taz',
                              'distance_to_work','workplace_in_cbd', 'work_taz_area_type', 'hh_race_of_head',
                             'roundtrip_auto_time_to_work','work_auto_savings_ratio','cdap_activity', 'travel_active', 
                              'under16_not_at_school','has_preschool_kid_at_home', 'block_id','gt2','hispanic_head',
                             'has_school_kid_at_home','work_and_school_and_worker', 'age_of_head', 'race_of_head',
                              'work_and_school_and_student', 'VEHICL','hh_children','hh_age_of_head','num_workers',
                              'gt55','seniors', 'recent_mover', 'hh_workers', 'hispanic_status_of_head', 'hh_seniors', 
                             'hh_type', 'TAZ_y', 'HHT', 'sample_rate', 'chunk_id', 'income_segment', 'num_non_workers', 
                             'num_drivers', 'num_adults', 'num_children', 'hh_work_auto_savings_ratio', 'num_travel_active', 
                             'num_travel_active_adults','num_travel_active_preschoolers', 'num_travel_active_children', 
                              'num_travel_active_non_preschoolers', 'participates_in_jtf_model', 'joint_tour_frequency',
                              'num_hh_joint_tours'], axis=1)

In [14]:
sf_stacked = sf_stacked.drop(['serialno'], axis=1)

In [19]:
sf_stacked.tail()

,IDMerged,tripIndex,actEndTime,actEndType,actStartTime,actStartType,cost_BEAM,distance_bike,distance_mode_choice,distance_privateCar,distance_ridehail,distance_transit,distance_travelling,distance_walking,duration_in_privateCar,duration_in_ridehail,duration_in_transit,duration_on_bike,duration_travelling,duration_walking,emissionBiodiesel,emissionDiesel,emissionElectricity,emissionFood,emissionGasoline,emission_marginal,fuelBiodiesel,fuelDiesel,fuelElectricity,fuelFood,fuelGasoline,fuel_marginal,fuel_not_Food,lever,lever_position_fleetsize,lever_position_price,mode_choice_actual_BEAM,mode_choice_planned_BEAM,numPassengers,parkingType,reason,replanning_status,ride_hail_pooled,scenario,transit_bus,transit_cable_car,transit_rail,transit_subway,transit_tram,vehicleIds,year,duration_door_to_door,waitTime,actPurpose,mode_choice_actual_5,mode_choice_actual_6,trip_id,person_id,household_id,tour_id,primary_purpose_x,trip_count,purpose,destination_logsum_x,trip_mode_AS_trips,logsum_trip_mode_AS_trips,tour_type,tour_category,household_id_x,start,end,duration,destination_logsum_y,tour_mode_AS_tours,logsum_tours_mode_AS_tours,primary_purpose_y,earning,person_sex,PNUM,sex,edu,race,work_at_home,age,value_of_time,workplace_location_logsum,work_auto_savings,free_parking_at_work,mandatory_tour_frequency,num_mand,num_work_tours,num_joint_tours,non_mandatory_tour_frequency,num_non_mand,num_escort_tours,num_eatout_tours,num_shop_tours,num_maint_tours,num_discr_tours,num_social_tours,num_non_escort_tours,lcm_county_id,tenure_mover,hh_size,sf_detached,tenure,hh_cars,income,hh_income,hhsize,income_in_thousands,median_value_of_time,hh_value_of_time,home_is_urban,home_is_rural,auto_ownership,DRIVEALONEFREE,DRIVEALONEPAY,SHARED2FREE,SHARED2PAY,SHARED3FREE,SHARED3PAY,WALK,BIKE,WALK_LOC,WALK_LRF,WALK_EXP,WALK_HVY,WALK_COM,DRIVE_LOC,DRIVE_LRF,DRIVE_EXP,DRIVE_HVY,DRIVE_COM,TAXI,TNC_SINGLE,TNC_SHARED,lever_position
7404487,7399583,2427063449.000000,30470.000000,Home,32623.000000,othmaint,21.858641,0.000000,32057.512000,0.000000,36681.848000,0.000000,36681.848000,0.000000,0.000000,1461.000000,0.000000,0.000000,1461.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.005245,0.000214,0.000000,0.000000,0.000000,0.000000,70961620.780906,68061218.785695,70961620.780906,price_fleetsize,0.250000,2.500000,ride_hail_pooled,ride_hail_pooled,"1.0, 2.0, 3.0, 1.0, 2.0",NaN,NaN,0,3,ridehail,0,0,0,0,0,"body-7399583, rideHailVehicle-657135@default",2018,2153.000000,692.000000,Home_to_othmaint,ride_hail,ride_hail,2427063449,7399583,2895003,303382931,othmaint,1,othmaint,NaN,WALK_HVY,-1.126718,othmaint,non_mandatory,2895003,8.000000,20.000000,12.000000,12.313683,WALK_HVY,-3.949918,othmaint,0.000000,female,1,2,19.000000,white,0,63,5.413348,NaN,0.000000,False,NaN,0,0,0,8,1,0,0,0,1,0,0,1,6081,own not recent,one,yes,1,one,50300.000000,gt30-lt60,1,50.300000,8.810000,5.413348,False,False,1,-1000.150066,-1000.162924,-36.559266,-36.566613,-31.270466,-31.275609,-65.809713,-1025.328488,-2.212943,-998.650467,-998.524867,-1.144793,-998.676767,-1000.627982,-1998.219067,-1998.219067,-1999.510615,-1998.219067,-13.167164,-19.960604,-12.468585,NaN
7404488,7399583,2427063449.000000,29008.000000,Home,30723.000000,othmaint,21.410720,0.000000,31110.301000,0.000000,33288.547000,0.000000,33288.547000,0.000000,0.000000,1264.000000,0.000000,0.000000,1264.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004251,0.004251,0.000000,0.000000,0.000000,0.000000,57517497.196784,57517497.196784,57517497.196784,default,1.000000,NaN,ride_hail_pooled,ride_hail_pooled,"1.0, 1.0, 1.0",NaN,NaN,0,3,baseline,0,0,0,0,0,"body-7399583, rideHailVehicle-937652@default",2018,1715.000000,451.000000,Home_to_othmaint,ride_hail,ride_hail,2427063449,7399583,2895003,303382931,othmaint,1,othmaint,NaN,WALK_HVY,-1.123955,othmaint,non_mandatory,2895003,8.000000,20.000000,12.000000,12.316087,WALK_HVY,-3.945758,othmaint,0.000000,female,1,2,19.000000,white,0,63,5.413348,NaN,0.000000,False,NaN,0,0,0,8,1,0,0,0,1,0,0,1,6081,own not recent,one,yes,1,one,50300.000000,gt30-lt60,1,50.300000,8.810000,5.413348,False,False,1,-1000.150066,-1000.162924,-36.559266,-36.566613,-31.270466,-31.275609,-65.809713,-1025.328488,-2.212943,-998.650467,-998.524867,-1.144793,-998.676767,-1000.627982,-1998.219067,-1998.219067,-1999.510615,-1998.219067,-13.202674,-10.063934,-7.012234,1.000000
7404489,7399583,2427063453.000000,74743.000000,othmaint,76450.000000,Home,19.669444,0.000000,33121.316000,0.000000,33750.818000,0.000000,33750.818000,0.000000,0.000000,1278.000000,0.000000,0.000000,1278.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004008,0.004008,0.000000,0.000000,0.000000,0.000000,54228956.163666,54228956.163666,54228956.163666,price_fleetsize,0.250000,1.500000,ride_hail_pooled,ride_hail_pooled,"1.0, 1.0, 1.0",NaN,NaN,0,3,ridehail,0,0,0,0,0,"rideHailVehicle-3149144@default, body-7399583",2018,1707.000000,429.000000,othmaint_to_Home,ride_hail,ride_hail,2427063453,7399583,2895003,303382931,othmaint,1,Home,NaN,TNC_SHARED,-8.519420,othmaint,non_mandatory,2895003,8.000000,20.000000,12.000000,12.314057,WALK_HVY,-3.949789,othmaint,0.000000,female,1,2,19.000000,white,0,63,5.413348,NaN,0.000000,False,NaN,0,0,0,8,1,0,0,0,1,0,0,1,6081,own not recent,one,yes,1,one,50300.000000,gt30-lt60,1,50.300000,8.810000,5.413348,False,False,1,-1001.365727,-1001.377062,-37.204925,-37.211401,-31.688123,-31.692657,-64.312963,-1024.580113,-999.430304,-998.650467,-998.524867,-999.830119,-998.676767,-1998.219067,-1998.219067,-1998.219067,-1998.219067,-1998.219067,-13.285549,-13.137363,-8.519422,NaN
7404490,7399583,2427063453.000000,75376.000000,othmaint,96174.000000,Home,0.000000,0.000000,93210.814288,0.000000,0.000000,0.000000,27563.715288,27563.715288,0.000000,0.000000,0.000000,0.000000,19974.000000,19974.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,price_fleetsize,0.250000,2.500000,walk,ride_hail_pooled,"1.0, 1.0, 1.0",NaN,"ResourceUnavailable RIDE_HAIL_POOLED, Resource...",2,2,ridehail,0,0,0,0,0,body-7399583,2018,20798.000000,824.000000,othmaint_to_Home,walk,walk,2427063453,7399583,2895003,303382931,othmaint,1,Home,NaN,TNC_SHARED,-11.698804,othmaint,non_mandatory,2895003,8.000000,20.000000,12.000000,12.313683,WALK_HVY,-3.949918,othmaint,0.000000,female,1,2,19.000000,white,0,63,5.413348,NaN,0.000000,False,NaN,0,0,0,8,1,0,0,0,1,0,0,1,6081,own not recent,one,yes,1,one,50300.000000,gt30-lt60,1,50.300000,8.810000,5.413348,False,False,1,-1001.365727,-1001.377062,-37.204925,-37.211401,-31.688123,-31.692657,-64.312963,-1024.580113,-999.430304,-998.650467,-998.524867,-999.830119,-998.676767,-1998.219067,-1998.219067,-1998.219067,-1998.219067,-1998.219067,-13.237850,-19.397479,-11.860989,NaN
7404491,7399583,2427063453.000000,75387.000000,othmaint,77104.000000,Home,19.565259,0.000000,33210.864000,0.000000,34154.695000,0.000000,34154.695000,0.000000,0.000000,1259.000000,0.000000,0.000000,1259.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004839,0.000000,0.000000,0.000000,0.000000,0.000000,65463608.315052,65463608.315052,65463608.315052,default,1.000000,NaN,ride_hail_pooled,ride_hail_pooled,"1.0, 1.0, 1.0",NaN,NaN,0,2,baseline,0,0,0,0,0,"body-7399583, rideHailVehicle-6170060@default",2018,1717.000000,458.000000,othmaint_to_Home,ride_hail,ride_hail,2427063453,7399583,2895003,303382931,othmaint,1,Home,NaN,TNC_SHARED,-6.723183,othmaint,non_mandatory,2895003,8.000000,20.000000,12.000000,12.316087,WALK_HVY,-3.945758,othmaint,0.000000,female,1,2,19.000000,white,0,63,5.413348,NaN,0.000000,False,NaN,0,0,0,8,1,0,0,0,1,0,0,1,6081,own not recent,one,yes,1,one,50300.000000,gt30-lt60,1,50.300000,8.810000,5.413348,False,False,1,-1001.365727,-1001.377062,-37.204925,-37.211401,-31.688123,-31.692657,-64.312963,-1024.580113,-999.430304,-998.650467,-998.524867,-999.830119,-998.676767,-1998.219067,-1998.219067,-1998.219067,-1998.219067,-1998.219067,-12.921627,-9.619534,-6.723299,1.000000

#### Stacked File

In [22]:
#stacked_tr_fr_path = "https://beam-core-act.s3.amazonaws.com/deepDive/CleanData/SanFrancisco/Stacked/"
#sf_stacked_tr_fr = pd.read_csv(stacked_tr_fr_path + 'sf_2018_stacked_tr_fr.csv')

In [18]:
sf_stacked['lever_position_fleetsize'] = np.where(sf_stacked['lever_position'] == 1, 1 , sf_stacked['lever_position_fleetsize'])

In [20]:
sf_stacked['lever_position_price'] = np.where(sf_stacked['lever_position'] == 1, 1 , sf_stacked['lever_position_price'])

In [21]:
sf_stacked = sf_stacked.sort_values(by=['IDMerged', 'tripIndex', 'lever_position_fleetsize', 'lever_position_price']).reset_index(drop=True)

In [22]:
# shift column 'person' to first position
first_column = sf_stacked.pop('scenario')
second_column = sf_stacked.pop('lever')
third_column = sf_stacked.pop('lever_position_fleetsize')
fourth_column = sf_stacked.pop('lever_position_price')
fifth_column = sf_stacked.pop('logsum_trip_mode_AS_trips')
# insert column using insert(position,column_name,first_column) function
sf_stacked.insert(2, 'scenario', first_column)
sf_stacked.insert(3, 'lever', second_column)
sf_stacked.insert(4, 'lever_position_fleetsize', third_column)
sf_stacked.insert(5, 'lever_position_price', fourth_column)
sf_stacked.insert(6, 'logsum_trip_mode_AS_trips', fifth_column)

In [23]:
#sf_stacked_tr_fr['logsum_relative_to_baseline'] = sf_stacked_tr_fr.groupby(['IDMerged','tripIndex'])['logsum_trip_mode_AS_trips'].apply(lambda x: x.diff())

In [24]:
#sf_stacked_tr_fr['logsum_relative_to_baseline'] = sf_stacked_tr_fr['logsum_trip_mode_AS_trips'] - sf_stacked_tr_fr.loc[sf_stacked_tr_fr.groupby(['IDMerged','tripIndex'])['lever_position'].transform('idxmin'), 'logsum_trip_mode_AS_trips'].values

In [28]:
%%time
sf_stacked['logsum_relative_to_baseline'] = sf_stacked['logsum_trip_mode_AS_trips'] - (sf_stacked['logsum_trip_mode_AS_trips'].where(sf_stacked['lever_position_fleetsize'].eq(1.0)&sf_stacked['lever_position_price'].eq(1.0))
                                                                                                  .groupby([sf_stacked['IDMerged'],sf_stacked['tripIndex']])
                                                                                                   .transform('first')
                                                                                                   .convert_dtypes())

CPU times: total: 2.47 s
Wall time: 2.37 s

In [29]:
sf_stacked['door_to_door_time_relative_to_baseline'] = sf_stacked['duration_door_to_door'] - (sf_stacked['duration_door_to_door'].where(sf_stacked['lever_position_fleetsize'].eq(1.0))
                                                                                                  .groupby([sf_stacked['IDMerged'],sf_stacked['tripIndex']])
                                                                                                   .transform('first')
                                                                                                   .convert_dtypes())

In [33]:
sf_stacked.head()

,IDMerged,tripIndex,scenario,lever,lever_position_fleetsize,logsum_relative_to_baseline,door_to_door_time_relative_to_baseline,income,actPurpose,lever_position_price,logsum_trip_mode_AS_trips,actEndTime,actEndType,actStartTime,actStartType,cost_BEAM,distance_bike,distance_mode_choice,distance_privateCar,distance_ridehail,distance_transit,distance_travelling,distance_walking,duration_in_privateCar,duration_in_ridehail,duration_in_transit,duration_on_bike,duration_travelling,duration_walking,emissionBiodiesel,emissionDiesel,emissionElectricity,emissionFood,emissionGasoline,emission_marginal,fuelBiodiesel,fuelDiesel,fuelElectricity,fuelFood,fuelGasoline,fuel_marginal,fuel_not_Food,mode_choice_actual_BEAM,mode_choice_planned_BEAM,numPassengers,parkingType,reason,replanning_status,ride_hail_pooled,transit_bus,transit_cable_car,transit_rail,transit_subway,transit_tram,vehicleIds,year,duration_door_to_door,waitTime,mode_choice_actual_5,mode_choice_actual_6,trip_id,person_id,household_id,tour_id,primary_purpose_x,trip_count,purpose,destination_logsum_x,trip_mode_AS_trips,tour_type,tour_category,household_id_x,start,end,duration,destination_logsum_y,tour_mode_AS_tours,logsum_tours_mode_AS_tours,primary_purpose_y,earning,person_sex,PNUM,sex,edu,race,work_at_home,age,value_of_time,workplace_location_logsum,work_auto_savings,free_parking_at_work,mandatory_tour_frequency,num_mand,num_work_tours,num_joint_tours,non_mandatory_tour_frequency,num_non_mand,num_escort_tours,num_eatout_tours,num_shop_tours,num_maint_tours,num_discr_tours,num_social_tours,num_non_escort_tours,lcm_county_id,tenure_mover,hh_size,sf_detached,tenure,hh_cars,hh_income,hhsize,income_in_thousands,median_value_of_time,hh_value_of_time,home_is_urban,home_is_rural,auto_ownership,DRIVEALONEFREE,DRIVEALONEPAY,SHARED2FREE,SHARED2PAY,SHARED3FREE,SHARED3PAY,WALK,BIKE,WALK_LOC,WALK_LRF,WALK_EXP,WALK_HVY,WALK_COM,DRIVE_LOC,DRIVE_LRF,DRIVE_EXP,DRIVE_HVY,DRIVE_COM,TAXI,TNC_SINGLE,TNC_SHARED,lever_position
0,1,577.000000,ridehail,price_fleetsize,0.250000,0.089552,-12.000000,240000.000000,Home_to_othmaint,1.500000,-2.287766,29293.000000,Home,29476.000000,othmaint,0.000000,0.000000,4632.391000,4632.391000,0.000000,0.000000,4632.391000,0.000000,183.000000,0.000000,0.000000,0.000000,183.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,183.000000,0.000000,car,car,577,1,1735309,72,school,2,othmaint,5.879557,SHARED2FREE,school,mandatory,1735309,8.000000,15.000000,7.000000,NaN,SHARED2PAY,-0.990567,school,0.000000,male,3,1,1.000000,asian,0,3,19.798008,NaN,0.000000,False,school1,1,0,0,0,0,0,0,0,0,0,0,0,6085,own not recent,four or more,yes,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.531774,-999.532278,-2.464308,-2.464596,-999.530422,-999.530623,-16.712076,-1001.492550,-1000.459856,-1998.770467,-1998.770467,-1998.770467,-1998.770467,-1999.307149,-2997.409495,-2997.409495,-2997.409495,-2997.409495,-8.620419,-8.994502,-9.672722,NaN
1,1,577.000000,ridehail,price_fleetsize,0.250000,0.494786,23.000000,240000.000000,Home_to_othmaint,2.500000,-1.882533,29361.000000,Home,29579.000000,othmaint,0.000000,0.000000,5382.075000,5382.075000,0.000000,0.000000,5382.075000,0.000000,218.000000,0.000000,0.000000,0.000000,218.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,218.000000,0.000000,car,car,577,1,1735309,72,school,2,othmaint,5.878180,SHARED2FREE,school,mandatory,1735309,8.000000,15.000000,7.000000,NaN,SHARED2PAY,-0.993618,school,0.000000,male,3,1,1.000000,asian,0,3,19.798008,NaN,0.000000,False,school1,1,0,0,0,0,0,0,0,0,0,0,0,6085,own not recent,four or more,yes,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.327077,-999.327369,-2.259611,-2.259778,-999.325724,-999.325841,-10.268612,-1000.848204,-1000.459856,-1998.770467,-1998.770467,-1998.770467,-1998.770467,-1999.307149,-2997.409495,-2997.409495,-2997.409495,-2997.409495,-8.111640,-9.024152,-11.861608,NaN
2,1,577.000000,baseline,default,1.000000,0.000000,0.000000,240000.000000,Home_to_othmaint,1.000000,-2.377319,31052.000000,Home,31247.000000,othmaint,0.000000,0.000000,4940.606000,4940.606000,0.000000,0.000000,4940.606000,0.000000,195.000000,0.000000,0.000000,0.000000,195.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,195.000000,0.000000,car,car,577,1,1735309,72,school,2,othmaint,5.881077,SHARED2FREE,school,mandatory,1735309,8.000000,15.000000,7.000000,NaN,SHARED2PAY,-0.983579,school,0.000000,male,3,1,1.000000,asian,0,3,19.798008,NaN,0.000000,False,school1,1,0,0,0,0,0,0,0,0,0,0,0,6085,own not recent,four or more,yes,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.621919,-999.622345,-2.554453,-2.554696,-999.620566,-999.620737,-38.227666,-1007.088933,-1000.459856,-1998.770467,-1998.770467,-1998.770467,-1998.770467,-1999.307149,-2997.409495,-2997.409495,-2997.409495,-2997.409495,-8.625908,-8.611274,-9.231232,1.000000
3,1,578.000000,ridehail,price_fleetsize,0.250000,-0.192297,7.000000,240000.000000,othmaint_to_school,1.500000,-2.388670,29721.000000,othmaint,30046.000000,school,0.000000,0.000000,7476.099000,7476.099000,0.000000,0.000000,7476.099000,0.000000,325.000000,0.000000,0.000000,0.000000,325.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,325.000000,0.000000,car,car,578,1,1735309,72,school,2,school,NaN,SHARED2FREE,school,mandatory,1735309,8.000000,15.000000,7.000000,NaN,SHARED2PAY,-0.990567,school,0.000000,male,3,1,1.000000,asian,0,3,19.798008,NaN,0.000000,False,school1,1,0,0,0,0,0,0,0,0,0,0,0,6085,own not recent,four or more,yes,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.632572,-999.633014,-2.565106,-2.565359,-999.631219,-999.631396,-17.437424,-1001.567111,-1001.491351,-1998.772718,-1999.043718,-1998.772718,-1998.772718,-1999.302789,-2997.411746,-2997.411746,-2997.411746,-2997.411746,-8.764279,-9.207617,-9.927299,NaN
4,1,578.000000,ridehail,price_fleetsize,0.250000,0.292889,-17.000000,240000.000000,othmaint_to_school,2.500000,-1.903483,29763.000000,othmaint,30064.000000,school,0.000000,0.000000,7678.068000,7678.068000,0.000000,0.000000,7678.068000,0.000000,301.000000,0.000000,0.000000,0.000000,301.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,301.000000,0.000000,car,car,578,1,1735309,72,school,2,school,NaN,SHARED2FREE,school,mandatory,1735309,8.000000,15.000000,7.000000,NaN,SHARED2PAY,-0.993618,school,0.000000,male,3,1,1.000000,asian,0,3,19.798008,NaN,0.000000,False,school1,1,0,0,0,0,0,0,0,0,0,0,0,6085,own not recent,four or more,yes,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.170302,-999.170803,-2.102836,-2.103123,-999.168950,-999.169150,-15.367260,-1001.360095,-1001.491351,-1998.772718,-1999.043718,-1998.772718,-1998.772718,-1999.302789,-2997.411746,-2997.411746,-2997.411746,-2997.411746,-8.059820,-8.797988,-9.175784,NaN

In [32]:
# shift columns to first position
first_column = sf_stacked.pop('logsum_relative_to_baseline')
second_column = sf_stacked.pop('door_to_door_time_relative_to_baseline')
third_column = sf_stacked.pop('income')
fourth_column = sf_stacked.pop('actPurpose')
# insert column using insert(position,column_name,first_column) function
sf_stacked.insert(5, 'logsum_relative_to_baseline', first_column)
sf_stacked.insert(6, 'door_to_door_time_relative_to_baseline', second_column)
sf_stacked.insert(7, 'income', third_column)
sf_stacked.insert(8, 'actPurpose', fourth_column)

In [34]:
# Drop unused columns
sf_stacked = sf_stacked.drop(['sf_detached','destination_logsum_x',
                                          'household_id_x','destination_logsum_y','logsum_tours_mode_AS_tours','primary_purpose_y',
                                          'PNUM','workplace_location_logsum','work_auto_savings','mandatory_tour_frequency','lever_position'], axis=1)

In [35]:
# Rename to potential INEXUS
sf_stacked.rename(columns={"logsum_trip_mode_AS_trips":"logsum_trip_potential_INEXUS"}, inplace=True)

In [36]:
# shift columns to first position
#first_column = sf_stacked_tr_fr.pop('mode_choice_actual_6')
second_column = sf_stacked.pop('mode_choice_actual_BEAM')
#third_column = sf_stacked_tr_fr.pop('income')
#fourth_column = sf_stacked_tr_fr.pop('actPurpose')
# insert column using insert(position,column_name,first_column) function
#sf_stacked_tr_fr.insert(9, 'mode_choice_actual_6', first_column)
sf_stacked.insert(10, 'mode_choice_actual_BEAM', second_column)
#sf_stacked_tr_fr.insert(11, 'income', third_column)
#sf_stacked_tr_fr.insert(12, 'actPurpose', fourth_column)

In [37]:
sf_stacked[sf_stacked['mode_choice_actual_6'] == 'ride_hail_transit'].shape

(1404, 129)

In [38]:
sf_stacked[sf_stacked['replanning_status'] > 0].shape

(25379, 129)

In [39]:
# Add the mandatory category column
mandatory = ['work' , 'univ', 'school']
sf_stacked['mandatoryCat'] = np.where((sf_stacked.actEndType.isin(mandatory)) & (sf_stacked.actStartType.isin(mandatory)), 'from_M_to_M' , None)

In [40]:
sf_stacked['mandatoryCat'] = np.where((sf_stacked.actEndType == 'Home') & (sf_stacked.actStartType.isin(mandatory)), 'from_H_to_M' , sf_stacked['mandatoryCat'])

In [41]:
sf_stacked['mandatoryCat'] = np.where((sf_stacked.actEndType.isin(mandatory)) & (sf_stacked.actStartType == "Home"), 'from_M_to_H' , sf_stacked['mandatoryCat'])

In [42]:
non_mandatory = ['othmaint' , 'othdiscr', 'escort', 'eatout', 'social', 'shopping', 'atwork']
sf_stacked['mandatoryCat'] = np.where((sf_stacked.actEndType.isin(non_mandatory)) & (sf_stacked.actStartType.isin(non_mandatory)), 'from_N_to_N' , sf_stacked['mandatoryCat'])

In [43]:
# shift columns to first position
first_column = sf_stacked.pop('mandatoryCat')
# insert column using insert(position,column_name,first_column) function
sf_stacked.insert(11, 'mandatoryCat', first_column)

In [44]:
# Drop unused columns
sf_stacked = sf_stacked.drop(['num_work_tours','num_joint_tours', 'non_mandatory_tour_frequency',
                                          'num_non_mand','num_escort_tours','num_eatout_tours','num_shop_tours',
                                          'num_maint_tours','num_discr_tours','num_social_tours','num_non_escort_tours'], axis=1)

In [45]:
sf_stacked.mode_choice_actual_BEAM.unique()

array(['hov2_teleportation', 'car', 'hov3_teleportation', 'walk',
       'car_hov2', 'walk_transit', 'drive_transit', 'ride_hail_pooled',
       'car_hov3', 'ride_hail', 'bike', 'ride_hail_transit',
       'bike_transit'], dtype=object)

In [46]:
sf_stacked.trip_mode_AS_trips.unique()

array(['SHARED2FREE', 'DRIVEALONEFREE', 'DRIVEALONEPAY', 'SHARED2PAY',
       'SHARED3PAY', 'SHARED3FREE', 'WALK', 'WALK_LOC', 'DRIVE_HVY',
       'TAXI', 'TNC_SHARED', 'WALK_LRF', 'WALK_HVY', 'BIKE', 'TNC_SINGLE',
       'WALK_COM', 'DRIVE_LRF', 'DRIVE_LOC', 'DRIVE_COM'], dtype=object)

In [47]:
# Rename to Potential INEXUS
sf_stacked.rename(columns={"logsum_trip_potential_INEXUS":"logsum_trip_Potential_INEXUS"}, inplace=True)

In [48]:
# Mapping BEAM and ASIM modes
conditions  = [(sf_stacked['mode_choice_actual_BEAM'] == 'walk'), 
               (sf_stacked['mode_choice_actual_BEAM'] == 'bike'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED3FREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED3PAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED3FREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED3PAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED2FREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED2PAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED2PAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED2FREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVEALONEFREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVEALONEPAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_LRF'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_LOC'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_EXP'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_HVY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail')&(sf_stacked['trip_mode_AS_trips'] == 'TNC_SINGLE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail')&(sf_stacked['trip_mode_AS_trips'] == 'TNC_SHARED'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail_pooled')&(sf_stacked['trip_mode_AS_trips'] == 'TNC_SINGLE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail')&(sf_stacked['trip_mode_AS_trips'] == 'TAXI'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_COM'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_COM'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LRF'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LOC'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_EXP'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_HVY')]

choices = [sf_stacked['WALK'], sf_stacked['BIKE'], sf_stacked['SHARED3FREE'], sf_stacked['SHARED3PAY'],
           sf_stacked['SHARED3FREE'], sf_stacked['SHARED3PAY'], sf_stacked['SHARED2FREE'], 
           sf_stacked['SHARED2PAY'], sf_stacked['SHARED2PAY'], sf_stacked['SHARED2FREE'], 
           sf_stacked['DRIVEALONEFREE'], sf_stacked['DRIVEALONEPAY'], sf_stacked['WALK_LRF'], 
           sf_stacked['WALK_LOC'], sf_stacked['WALK_EXP'], sf_stacked['WALK_HVY'], sf_stacked['TNC_SINGLE'], 
           sf_stacked['TNC_SHARED'], sf_stacked['TNC_SINGLE'], sf_stacked['TAXI'], sf_stacked['WALK_COM'], 
           sf_stacked['DRIVE_COM'], sf_stacked['DRIVE_LRF'], sf_stacked['DRIVE_LOC'], sf_stacked['DRIVE_EXP'],
           sf_stacked['DRIVE_HVY']]

In [49]:
sf_stacked['Realized_INEXUS'] = np.select(conditions, choices, default=np.nan)

In [50]:
# shift columns to first position
first_column = sf_stacked.pop('Realized_INEXUS')
# insert column using insert(position,column_name,first_column) function
sf_stacked.insert(5, 'Realized_INEXUS', first_column)

In [51]:
sf_stacked.head()

,IDMerged,tripIndex,scenario,lever,lever_position_fleetsize,Realized_INEXUS,logsum_relative_to_baseline,door_to_door_time_relative_to_baseline,income,actPurpose,lever_position_price,mode_choice_actual_BEAM,mandatoryCat,logsum_trip_Potential_INEXUS,actEndTime,actEndType,actStartTime,actStartType,cost_BEAM,distance_bike,distance_mode_choice,distance_privateCar,distance_ridehail,distance_transit,distance_travelling,distance_walking,duration_in_privateCar,duration_in_ridehail,duration_in_transit,duration_on_bike,duration_travelling,duration_walking,emissionBiodiesel,emissionDiesel,emissionElectricity,emissionFood,emissionGasoline,emission_marginal,fuelBiodiesel,fuelDiesel,fuelElectricity,fuelFood,fuelGasoline,fuel_marginal,fuel_not_Food,mode_choice_planned_BEAM,numPassengers,parkingType,reason,replanning_status,ride_hail_pooled,transit_bus,transit_cable_car,transit_rail,transit_subway,transit_tram,vehicleIds,year,duration_door_to_door,waitTime,mode_choice_actual_5,mode_choice_actual_6,trip_id,person_id,household_id,tour_id,primary_purpose_x,trip_count,purpose,trip_mode_AS_trips,tour_type,tour_category,start,end,duration,tour_mode_AS_tours,earning,person_sex,sex,edu,race,work_at_home,age,value_of_time,free_parking_at_work,num_mand,lcm_county_id,tenure_mover,hh_size,tenure,hh_cars,hh_income,hhsize,income_in_thousands,median_value_of_time,hh_value_of_time,home_is_urban,home_is_rural,auto_ownership,DRIVEALONEFREE,DRIVEALONEPAY,SHARED2FREE,SHARED2PAY,SHARED3FREE,SHARED3PAY,WALK,BIKE,WALK_LOC,WALK_LRF,WALK_EXP,WALK_HVY,WALK_COM,DRIVE_LOC,DRIVE_LRF,DRIVE_EXP,DRIVE_HVY,DRIVE_COM,TAXI,TNC_SINGLE,TNC_SHARED
0,1,577.000000,ridehail,price_fleetsize,0.250000,-2.464308,0.089552,-12.000000,240000.000000,Home_to_othmaint,1.500000,hov2_teleportation,None,-2.287766,29293.000000,Home,29476.000000,othmaint,0.000000,0.000000,4632.391000,4632.391000,0.000000,0.000000,4632.391000,0.000000,183.000000,0.000000,0.000000,0.000000,183.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,183.000000,0.000000,car,car,577,1,1735309,72,school,2,othmaint,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.531774,-999.532278,-2.464308,-2.464596,-999.530422,-999.530623,-16.712076,-1001.492550,-1000.459856,-1998.770467,-1998.770467,-1998.770467,-1998.770467,-1999.307149,-2997.409495,-2997.409495,-2997.409495,-2997.409495,-8.620419,-8.994502,-9.672722
1,1,577.000000,ridehail,price_fleetsize,0.250000,-2.259611,0.494786,23.000000,240000.000000,Home_to_othmaint,2.500000,hov2_teleportation,None,-1.882533,29361.000000,Home,29579.000000,othmaint,0.000000,0.000000,5382.075000,5382.075000,0.000000,0.000000,5382.075000,0.000000,218.000000,0.000000,0.000000,0.000000,218.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,218.000000,0.000000,car,car,577,1,1735309,72,school,2,othmaint,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.327077,-999.327369,-2.259611,-2.259778,-999.325724,-999.325841,-10.268612,-1000.848204,-1000.459856,-1998.770467,-1998.770467,-1998.770467,-1998.770467,-1999.307149,-2997.409495,-2997.409495,-2997.409495,-2997.409495,-8.111640,-9.024152,-11.861608
2,1,577.000000,baseline,default,1.000000,-2.554453,0.000000,0.000000,240000.000000,Home_to_othmaint,1.000000,hov2_teleportation,None,-2.377319,31052.000000,Home,31247.000000,othmaint,0.000000,0.000000,4940.606000,4940.606000,0.000000,0.000000,4940.606000,0.000000,195.000000,0.000000,0.000000,0.000000,195.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,195.000000,0.000000,car,car,577,1,1735309,72,school,2,othmaint,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.621919,-999.622345,-2.554453,-2.554696,-999.620566,-999.620737,-38.227666,-1007.088933,-1000.459856,-1998.770467,-1998.770467,-1998.770467,-1998.770467,-1999.307149,-2997.409495,-2997.409495,-2997.409495,-2997.409495,-8.625908,-8.611274,-9.231232
3,1,578.000000,ridehail,price_fleetsize,0.250000,-2.565106,-0.192297,7.000000,240000.000000,othmaint_to_school,1.500000,hov2_teleportation,None,-2.388670,29721.000000,othmaint,30046.000000,school,0.000000,0.000000,7476.099000,7476.099000,0.000000,0.000000,7476.099000,0.000000,325.000000,0.000000,0.000000,0.000000,325.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,325.000000,0.000000,car,car,578,1,1735309,72,school,2,school,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.632572,-999.633014,-2.565106,-2.565359,-999.631219,-999.631396,-17.437424,-1001.567111,-1001.491351,-1998.772718,-1999.043718,-1998.772718,-1998.772718,-1999.302789,-2997.411746,-2997.411746,-2997.411746,-2997.411746,-8.764279,-9.207617,-9.927299
4,1,578.000000,ridehail,price_fleetsize,0.250000,-2.102836,0.292889,-17.000000,240000.000000,othmaint_to_school,2.500000,hov2_teleportation,None,-1.903483,29763.000000,othmaint,30064.000000,school,0.000000,0.000000,7678.068000,7678.068000,0.000000,0.000000,7678.068000,0.000000,301.000000,0.000000,0.000000,0.000000,301.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,301.000000,0.000000,car,car,578,1,1735309,72,school,2,school,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.170302,-999.170803,-2.102836,-2.103123,-999.168950,-999.169150,-15.367260,-1001.360095,-1001.491351,-1998.772718,-1999.043718,-1998.772718,-1998.772718,-1999.302789,-2997.411746,-2997.411746,-2997.411746,-2997.411746,-8.059820,-8.797988,-9.175784

In [52]:
sf_stacked[sf_stacked['Realized_INEXUS'].isna()].shape

(1307553, 120)

In [53]:
#sf_stacked[sf_stacked['Realized_INEXUS'].isna()].head(10000).to_csv('C:/Shared-Work/Data/CleanData/ASIM_BEAM_Merged/realizedIN_empty.csv', index = False)

In [54]:
#%%time
#sf_stacked_tr_fr.to_csv('s3://beam-core-act/deepDive/CleanData/SanFrancisco/Stacked/sf_2018_stacked_tr_fr_v3.csv', index=False)

In [55]:
sf_stacked = sf_stacked[sf_stacked['trip_mode_AS_trips'].notna()]

In [56]:
sf_stacked = sf_stacked.drop(['Realized_INEXUS'], axis=1)

In [57]:
# Mapping BEAM and ASIM modes
conditions  = [(sf_stacked['mode_choice_actual_BEAM'] == 'walk'), 
               (sf_stacked['mode_choice_actual_BEAM'] == 'bike'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED3FREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED3PAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED3FREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED3PAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED2FREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED2PAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED2PAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED2FREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVEALONEFREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVEALONEPAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_LRF'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_LOC'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_EXP'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_HVY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail')&(sf_stacked['trip_mode_AS_trips'] == 'TNC_SINGLE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail')&(sf_stacked['trip_mode_AS_trips'] == 'TNC_SHARED'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail')&(sf_stacked['trip_mode_AS_trips'] == 'TAXI'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_COM'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_COM'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LRF'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LOC'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_EXP'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_HVY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED2FREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED2PAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED3PAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED3FREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED3PAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED2FREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED2PAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED3FREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED3PAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED3FREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVEALONEPAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVEALONEFREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVEALONEFREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVEALONEPAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED2FREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVEALONEPAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVEALONEFREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVEALONEFREE'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVEALONEPAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'SHARED2PAY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail_pooled')&(sf_stacked['ride_hail_pooled'] > 1),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'WALK'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked['trip_mode_AS_trips'] == 'WALK'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov2')&((sf_stacked['trip_mode_AS_trips'] == 'WALK_HVY')|
                    (sf_stacked['trip_mode_AS_trips'] == 'WALK_COM')|(sf_stacked['trip_mode_AS_trips'] == 'WALK_EXP')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_COM')|(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_EXP')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_HVY')|(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LOC')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LRF')|(sf_stacked['trip_mode_AS_trips'] == 'WALK_LRF')| 
                    (sf_stacked['trip_mode_AS_trips'] == 'WALK_LOC')|(sf_stacked['trip_mode_AS_trips'] == 'WALK')|
                    (sf_stacked['trip_mode_AS_trips'] == 'BIKE')|(sf_stacked['trip_mode_AS_trips'] == 'TNC_SINGLE')|
                    (sf_stacked['trip_mode_AS_trips'] == 'TNC_SHARED')|(sf_stacked['trip_mode_AS_trips'] == 'TAXI'))
                    & (sf_stacked['cost_BEAM'] > 2.5),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov3')&((sf_stacked['trip_mode_AS_trips'] == 'WALK_HVY')|
                    (sf_stacked['trip_mode_AS_trips'] == 'WALK_COM')|(sf_stacked['trip_mode_AS_trips'] == 'WALK_EXP')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_COM')|(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_EXP')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_HVY')|(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LOC')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LRF')|(sf_stacked['trip_mode_AS_trips'] == 'WALK_LRF')| 
                    (sf_stacked['trip_mode_AS_trips'] == 'WALK_LOC')|(sf_stacked['trip_mode_AS_trips'] == 'WALK')|
                    (sf_stacked['trip_mode_AS_trips'] == 'BIKE')|(sf_stacked['trip_mode_AS_trips'] == 'TNC_SINGLE')|
                    (sf_stacked['trip_mode_AS_trips'] == 'TNC_SHARED')|(sf_stacked['trip_mode_AS_trips'] == 'TAXI'))
                    & (sf_stacked['cost_BEAM'] > 2.5),
              (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov2')&((sf_stacked['trip_mode_AS_trips'] == 'WALK_HVY')|
                    (sf_stacked['trip_mode_AS_trips'] == 'WALK_COM')|(sf_stacked['trip_mode_AS_trips'] == 'WALK_EXP')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_COM')|(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_EXP')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_HVY')|(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LOC')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LRF')|(sf_stacked['trip_mode_AS_trips'] == 'WALK_LRF')| 
                    (sf_stacked['trip_mode_AS_trips'] == 'WALK_LOC')|(sf_stacked['trip_mode_AS_trips'] == 'WALK')|
                    (sf_stacked['trip_mode_AS_trips'] == 'BIKE')|(sf_stacked['trip_mode_AS_trips'] == 'TNC_SINGLE')|
                    (sf_stacked['trip_mode_AS_trips'] == 'TNC_SHARED')|(sf_stacked['trip_mode_AS_trips'] == 'TAXI'))
                    & (sf_stacked['cost_BEAM'] <= 2.5),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car_hov3')&((sf_stacked['trip_mode_AS_trips'] == 'WALK_HVY')|
                    (sf_stacked['trip_mode_AS_trips'] == 'WALK_COM')|(sf_stacked['trip_mode_AS_trips'] == 'WALK_EXP')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_COM')|(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_EXP')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_HVY')|(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LOC')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LRF')|(sf_stacked['trip_mode_AS_trips'] == 'WALK_LRF')| 
                    (sf_stacked['trip_mode_AS_trips'] == 'WALK_LOC')|(sf_stacked['trip_mode_AS_trips'] == 'WALK')|
                    (sf_stacked['trip_mode_AS_trips'] == 'BIKE')|(sf_stacked['trip_mode_AS_trips'] == 'TNC_SINGLE')|
                    (sf_stacked['trip_mode_AS_trips'] == 'TNC_SHARED')|(sf_stacked['trip_mode_AS_trips'] == 'TAXI'))
                    & (sf_stacked['cost_BEAM'] <= 2.5),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car')&((sf_stacked['trip_mode_AS_trips'] == 'WALK_HVY')|
                    (sf_stacked['trip_mode_AS_trips'] == 'WALK_COM')|(sf_stacked['trip_mode_AS_trips'] == 'WALK_EXP')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_COM')|(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_EXP')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_HVY')|(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LOC')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LRF')|(sf_stacked['trip_mode_AS_trips'] == 'WALK_LRF')| 
                    (sf_stacked['trip_mode_AS_trips'] == 'WALK_LOC')|(sf_stacked['trip_mode_AS_trips'] == 'WALK')|
                    (sf_stacked['trip_mode_AS_trips'] == 'BIKE')|(sf_stacked['trip_mode_AS_trips'] == 'TNC_SINGLE')|
                    (sf_stacked['trip_mode_AS_trips'] == 'TNC_SHARED')|(sf_stacked['trip_mode_AS_trips'] == 'TAXI'))
                    & (sf_stacked['cost_BEAM'] <= 2.5),
               (sf_stacked['mode_choice_actual_BEAM'] == 'car')&((sf_stacked['trip_mode_AS_trips'] == 'WALK_HVY')|
                    (sf_stacked['trip_mode_AS_trips'] == 'WALK_COM')|(sf_stacked['trip_mode_AS_trips'] == 'WALK_EXP')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_COM')|(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_EXP')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_HVY')|(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LOC')|
                    (sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LRF')|(sf_stacked['trip_mode_AS_trips'] == 'WALK_LRF')| 
                    (sf_stacked['trip_mode_AS_trips'] == 'WALK_LOC')|(sf_stacked['trip_mode_AS_trips'] == 'WALK')|
                    (sf_stacked['trip_mode_AS_trips'] == 'BIKE')|(sf_stacked['trip_mode_AS_trips'] == 'TNC_SINGLE')|
                    (sf_stacked['trip_mode_AS_trips'] == 'TNC_SHARED')|(sf_stacked['trip_mode_AS_trips'] == 'TAXI'))
                    & (sf_stacked['cost_BEAM'] > 2.5),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail_pooled'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_COM'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LRF'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_LOC'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_EXP'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked['trip_mode_AS_trips'] == 'DRIVE_HVY'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_COM'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_LRF'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_LOC'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_EXP'),
               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked['trip_mode_AS_trips'] == 'WALK_HVY')]
        
choices = [sf_stacked['WALK'], sf_stacked['BIKE'], sf_stacked['SHARED3FREE'], sf_stacked['SHARED3PAY'],
           sf_stacked['SHARED3FREE'], sf_stacked['SHARED3PAY'], sf_stacked['SHARED2FREE'], 
           sf_stacked['SHARED2PAY'], sf_stacked['SHARED2PAY'], sf_stacked['SHARED2FREE'], 
           sf_stacked['DRIVEALONEFREE'], sf_stacked['DRIVEALONEPAY'], sf_stacked['WALK_LRF'], 
           sf_stacked['WALK_LOC'], sf_stacked['WALK_EXP'], sf_stacked['WALK_HVY'], sf_stacked['TNC_SINGLE'], 
           sf_stacked['TNC_SHARED'], sf_stacked['TAXI'], sf_stacked['WALK_COM'], 
           sf_stacked['DRIVE_COM'], sf_stacked['DRIVE_LRF'], sf_stacked['DRIVE_LOC'], sf_stacked['DRIVE_EXP'],
           sf_stacked['DRIVE_HVY'], sf_stacked['SHARED3FREE'], sf_stacked['DRIVEALONEPAY'], sf_stacked['DRIVEALONEPAY'],
           sf_stacked['SHARED2FREE'], sf_stacked['SHARED2PAY'], sf_stacked['SHARED3FREE'],  sf_stacked['SHARED3PAY'],
           sf_stacked['SHARED2FREE'], sf_stacked['SHARED2PAY'], sf_stacked['DRIVEALONEFREE'], sf_stacked['SHARED2PAY'], 
           sf_stacked['SHARED2FREE'], sf_stacked['SHARED2FREE'], sf_stacked['SHARED2PAY'], sf_stacked['DRIVEALONEFREE'], 
           sf_stacked['SHARED3PAY'], sf_stacked['SHARED3FREE'], sf_stacked['SHARED3FREE'], sf_stacked['SHARED3PAY'],
           sf_stacked['SHARED3PAY'], sf_stacked['TNC_SHARED'], sf_stacked['SHARED3FREE'], sf_stacked['SHARED2FREE'],
           sf_stacked['SHARED2PAY'], sf_stacked['SHARED3PAY'], sf_stacked['SHARED2FREE'],sf_stacked['SHARED3FREE'],
           sf_stacked['DRIVEALONEFREE'], sf_stacked['DRIVEALONEPAY'], sf_stacked['TNC_SHARED'], sf_stacked['DRIVE_COM'],
           sf_stacked['DRIVE_LRF'], sf_stacked['DRIVE_LOC'], sf_stacked['DRIVE_EXP'], sf_stacked['DRIVE_HVY'],
           sf_stacked['WALK_COM'], sf_stacked['WALK_LRF'], sf_stacked['WALK_LOC'], sf_stacked['WALK_EXP'],
           sf_stacked['WALK_HVY']]

In [58]:
sf_stacked['Realized_INEXUS'] = np.select(conditions, choices, default=np.nan)

In [59]:
# shift columns to first position
first_column = sf_stacked.pop('Realized_INEXUS')
# insert column using insert(position,column_name,first_column) function
sf_stacked.insert(5, 'Realized_INEXUS', first_column)

In [60]:
sf_stacked['Realized_INEXUS'] = np.where((sf_stacked['Realized_INEXUS'].isna())&
                                               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail')&
                                               ((sf_stacked['numPassengers'] == '1.0, 1.0, 1.0')|
                                                (sf_stacked['numPassengers'] =='1.0, 1.0, 1.0, 1.0')|
                                                (sf_stacked['numPassengers'] =='1.0, 1.0, 1.0, 1.0, 1.0')|
                                                (sf_stacked['numPassengers'] =='1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0')|
                                                (sf_stacked['numPassengers'] =='1.0, 8.0, 8.0, 7.0, 1.0, 1.0, 1.0, 1.0')|
                                                (sf_stacked['numPassengers'] =='1.0, 16.0, 1.0, 1.0, 1.0, 1.0')|
                                                (sf_stacked['numPassengers'] =='1.0, 10.0, 11.0, 1.0, 1.0, 1.0, 1.0')), 
                                                sf_stacked['TNC_SINGLE'], sf_stacked['Realized_INEXUS'])

In [61]:
sf_stacked['Realized_INEXUS'] = np.where((sf_stacked['Realized_INEXUS'].isna())&
                                               (sf_stacked['mode_choice_actual_BEAM'] == 'hov2_teleportation'), 
                                                sf_stacked.loc[:, ["SHARED2FREE", "SHARED2PAY"]].max(1), sf_stacked['Realized_INEXUS'])

In [62]:
sf_stacked['Realized_INEXUS'] = np.where((sf_stacked['Realized_INEXUS'].isna())&
                                               (sf_stacked['mode_choice_actual_BEAM'] == 'hov3_teleportation'), 
                                                sf_stacked.loc[:, ["SHARED3FREE", "SHARED3PAY"]].max(1), sf_stacked['Realized_INEXUS'])

In [63]:
sf_stacked['Realized_INEXUS'] = np.where((sf_stacked['Realized_INEXUS'].isna())&
                                               (sf_stacked['mode_choice_actual_BEAM'] == 'walk_transit'), 
                                                sf_stacked.loc[:, ["WALK_COM", "WALK_LRF", "WALK_LOC", "WALK_EXP",
                                                      "WALK_HVY"]].max(1), sf_stacked['Realized_INEXUS'])

In [64]:
sf_stacked['Realized_INEXUS'] = np.where((sf_stacked['Realized_INEXUS'].isna())&
                                               (sf_stacked['mode_choice_actual_BEAM'] == 'drive_transit'), 
                                                sf_stacked.loc[:, ["DRIVE_COM", "DRIVE_LRF", "DRIVE_LOC", "DRIVE_EXP",
                                                      "DRIVE_HVY"]].max(1), sf_stacked['Realized_INEXUS'])

In [65]:
sf_stacked['Realized_INEXUS'] = np.where((sf_stacked['Realized_INEXUS'].isna())&
                                               (sf_stacked['mode_choice_actual_BEAM'] == 'bike_transit')&
                                               (sf_stacked['trip_mode_AS_trips'] == 'BIKE'), 
                                                sf_stacked['BIKE'], sf_stacked['Realized_INEXUS'])

In [66]:
sf_stacked['Realized_INEXUS'] = np.where((sf_stacked['Realized_INEXUS'].isna())&
                                               (sf_stacked['mode_choice_actual_BEAM'] == 'bike_transit')&
                                               (sf_stacked['trip_mode_AS_trips'] == 'BIKE'), 
                                                sf_stacked['BIKE'], sf_stacked['Realized_INEXUS'])

In [67]:
sf_stacked['Realized_INEXUS'] = np.where((sf_stacked['Realized_INEXUS'].isna())&
                                               (sf_stacked['mode_choice_actual_BEAM'] == 'ride_hail'), 
                                                sf_stacked['TNC_SINGLE'], sf_stacked['Realized_INEXUS'])

In [68]:
sf_stacked[sf_stacked['Realized_INEXUS'].isna()].shape

(20064, 120)

In [69]:
#sf_stacked_tr_fr['Realized_INEXUS'] = np.where((sf_stacked_tr_fr['Realized_INEXUS'].isna())&
                                               #(sf_stacked_tr_fr['mode_choice_actual_BEAM'] == 'walk_transit')&
                                               #(sf_stacked_tr_fr['vehicleIds'].str.contains('(caltrain)')), 
                                               #sf_stacked_tr_fr['WALK_COM'], sf_stacked_tr_fr['Realized_INEXUS'])

In [70]:
sf_stacked = sf_stacked[sf_stacked['Realized_INEXUS'].notna()]

In [66]:
#sf_stacked_tr_fr[sf_stacked_tr_fr['Realized_INEXUS'].isna()].to_csv('C:/Shared-Work/Data/CleanData/ASIM_BEAM_Merged/realizedIN_empty.csv', index = False)

#### Social INEXUS

In [71]:
sf_stacked.income.quantile([0, 0.25,0.5,0.75, 1.00])

0.000000    -14600.000000
0.250000     50000.000000
0.500000     94000.000000
0.750000    155000.000000
1.000000   1354000.000000
Name: income, dtype: float64

In [72]:
# determine the quartile values to use with pd.cut
quartiles = sf_stacked['income'].quantile([.25, .5, .75]).tolist()

In [73]:
# add a lower and upper range for the bins in pd.cut
quartiles = [0] + quartiles + [float('inf')]

In [74]:
# add a quartiles column to groups, using pd.cut
sf_stacked['income_quartiles'] = pd.cut(sf_stacked['income'], bins=quartiles, labels=['1stQ', '2ndQ', '3rdQ', '4thQ'])

In [75]:
sf_stacked.head()

,IDMerged,tripIndex,scenario,lever,lever_position_fleetsize,Realized_INEXUS,logsum_relative_to_baseline,door_to_door_time_relative_to_baseline,income,actPurpose,lever_position_price,mode_choice_actual_BEAM,mandatoryCat,logsum_trip_Potential_INEXUS,actEndTime,actEndType,actStartTime,actStartType,cost_BEAM,distance_bike,distance_mode_choice,distance_privateCar,distance_ridehail,distance_transit,distance_travelling,distance_walking,duration_in_privateCar,duration_in_ridehail,duration_in_transit,duration_on_bike,duration_travelling,duration_walking,emissionBiodiesel,emissionDiesel,emissionElectricity,emissionFood,emissionGasoline,emission_marginal,fuelBiodiesel,fuelDiesel,fuelElectricity,fuelFood,fuelGasoline,fuel_marginal,fuel_not_Food,mode_choice_planned_BEAM,numPassengers,parkingType,reason,replanning_status,ride_hail_pooled,transit_bus,transit_cable_car,transit_rail,transit_subway,transit_tram,vehicleIds,year,duration_door_to_door,waitTime,mode_choice_actual_5,mode_choice_actual_6,trip_id,person_id,household_id,tour_id,primary_purpose_x,trip_count,purpose,trip_mode_AS_trips,tour_type,tour_category,start,end,duration,tour_mode_AS_tours,earning,person_sex,sex,edu,race,work_at_home,age,value_of_time,free_parking_at_work,num_mand,lcm_county_id,tenure_mover,hh_size,tenure,hh_cars,hh_income,hhsize,income_in_thousands,median_value_of_time,hh_value_of_time,home_is_urban,home_is_rural,auto_ownership,DRIVEALONEFREE,DRIVEALONEPAY,SHARED2FREE,SHARED2PAY,SHARED3FREE,SHARED3PAY,WALK,BIKE,WALK_LOC,WALK_LRF,WALK_EXP,WALK_HVY,WALK_COM,DRIVE_LOC,DRIVE_LRF,DRIVE_EXP,DRIVE_HVY,DRIVE_COM,TAXI,TNC_SINGLE,TNC_SHARED,income_quartiles
0,1,577.000000,ridehail,price_fleetsize,0.250000,-2.464308,0.089552,-12.000000,240000.000000,Home_to_othmaint,1.500000,hov2_teleportation,None,-2.287766,29293.000000,Home,29476.000000,othmaint,0.000000,0.000000,4632.391000,4632.391000,0.000000,0.000000,4632.391000,0.000000,183.000000,0.000000,0.000000,0.000000,183.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,183.000000,0.000000,car,car,577,1,1735309,72,school,2,othmaint,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.531774,-999.532278,-2.464308,-2.464596,-999.530422,-999.530623,-16.712076,-1001.492550,-1000.459856,-1998.770467,-1998.770467,-1998.770467,-1998.770467,-1999.307149,-2997.409495,-2997.409495,-2997.409495,-2997.409495,-8.620419,-8.994502,-9.672722,4thQ
1,1,577.000000,ridehail,price_fleetsize,0.250000,-2.259611,0.494786,23.000000,240000.000000,Home_to_othmaint,2.500000,hov2_teleportation,None,-1.882533,29361.000000,Home,29579.000000,othmaint,0.000000,0.000000,5382.075000,5382.075000,0.000000,0.000000,5382.075000,0.000000,218.000000,0.000000,0.000000,0.000000,218.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,218.000000,0.000000,car,car,577,1,1735309,72,school,2,othmaint,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.327077,-999.327369,-2.259611,-2.259778,-999.325724,-999.325841,-10.268612,-1000.848204,-1000.459856,-1998.770467,-1998.770467,-1998.770467,-1998.770467,-1999.307149,-2997.409495,-2997.409495,-2997.409495,-2997.409495,-8.111640,-9.024152,-11.861608,4thQ
2,1,577.000000,baseline,default,1.000000,-2.554453,0.000000,0.000000,240000.000000,Home_to_othmaint,1.000000,hov2_teleportation,None,-2.377319,31052.000000,Home,31247.000000,othmaint,0.000000,0.000000,4940.606000,4940.606000,0.000000,0.000000,4940.606000,0.000000,195.000000,0.000000,0.000000,0.000000,195.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,195.000000,0.000000,car,car,577,1,1735309,72,school,2,othmaint,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.621919,-999.622345,-2.554453,-2.554696,-999.620566,-999.620737,-38.227666,-1007.088933,-1000.459856,-1998.770467,-1998.770467,-1998.770467,-1998.770467,-1999.307149,-2997.409495,-2997.409495,-2997.409495,-2997.409495,-8.625908,-8.611274,-9.231232,4thQ
3,1,578.000000,ridehail,price_fleetsize,0.250000,-2.565106,-0.192297,7.000000,240000.000000,othmaint_to_school,1.500000,hov2_teleportation,None,-2.388670,29721.000000,othmaint,30046.000000,school,0.000000,0.000000,7476.099000,7476.099000,0.000000,0.000000,7476.099000,0.000000,325.000000,0.000000,0.000000,0.000000,325.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,325.000000,0.000000,car,car,578,1,1735309,72,school,2,school,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.632572,-999.633014,-2.565106,-2.565359,-999.631219,-999.631396,-17.437424,-1001.567111,-1001.491351,-1998.772718,-1999.043718,-1998.772718,-1998.772718,-1999.302789,-2997.411746,-2997.411746,-2997.411746,-2997.411746,-8.764279,-9.207617,-9.927299,4thQ
4,1,578.000000,ridehail,price_fleetsize,0.250000,-2.102836,0.292889,-17.000000,240000.000000,othmaint_to_school,2.500000,hov2_teleportation,None,-1.903483,29763.000000,othmaint,30064.000000,school,0.000000,0.000000,7678.068000,7678.068000,0.000000,0.000000,7678.068000,0.000000,301.000000,0.000000,0.000000,0.000000,301.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,301.000000,0.000000,car,car,578,1,1735309,72,school,2,school,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.170302,-999.170803,-2.102836,-2.103123,-999.168950,-999.169150,-15.367260,-1001.360095,-1001.491351,-1998.772718,-1999.043718,-1998.772718,-1998.772718,-1999.302789,-2997.411746,-2997.411746,-2997.411746,-2997.411746,-8.059820,-8.797988,-9.175784,4thQ

In [76]:
m = sf_stacked.groupby(['income_quartiles'])['income'].median()

In [77]:
m

income_quartiles
1stQ    30000.000000
2ndQ    70600.000000
3rdQ   120000.000000
4thQ   219000.000000
Name: income, dtype: float64

In [78]:
# Mapping BEAM and ASIM modes
conditions  = [(sf_stacked['income_quartiles'] == '1stQ'), 
               (sf_stacked['income_quartiles'] == '2ndQ'),
               (sf_stacked['income_quartiles'] == '3rdQ'),
               (sf_stacked['income_quartiles'] == '4thQ')]

choices = [29300, 70000, 120000, 219000]

In [79]:
sf_stacked['MedianQuartiles'] = np.select(conditions, choices, default=np.nan)

In [80]:
sf_stacked['alpha'] = 0.1

In [81]:
sf_stacked['socialCarbonCost'] = sf_stacked['emission_marginal']*51 # or 102

In [82]:
sf_stacked['Social_INEXUS'] = (sf_stacked['Realized_INEXUS']/sf_stacked['alpha']) - sf_stacked['socialCarbonCost']

In [86]:
sf_stacked['Potential_INEXUS_in_dollar'] = sf_stacked['logsum_trip_Potential_INEXUS']/sf_stacked['alpha']

In [87]:
sf_stacked['Realized_INEXUS_in_dollar'] = sf_stacked['Realized_INEXUS']/sf_stacked['alpha']

#### The following chunks are useful but should be checked in the next runs (they resulted in exact same realized and potential inexus in dollar

In [122]:
# shift columns to first position
#first_column = sf_stacked.pop('Social_INEXUS')
# insert column using insert(position,column_name,first_column) function
#sf_stacked.insert(6, 'Social_INEXUS', first_column)

In [117]:
# shift columns to first position
#first_column = sf_stacked.pop('Potential_INEXUS_in_dollar')
#second_column = sf_stacked.pop('Realized_INEXUS_in_dollar')
# insert column using insert(position,column_name,first_column) function
#sf_stacked.insert(7, 'Potential_INEXUS_in_dollar', first_column)
#sf_stacked.insert(8, 'Realized_INEXUS_in_dollar', first_column)

In [88]:
sf_stacked.head()

,IDMerged,tripIndex,scenario,lever,lever_position_fleetsize,Realized_INEXUS,logsum_relative_to_baseline,door_to_door_time_relative_to_baseline,income,actPurpose,lever_position_price,mode_choice_actual_BEAM,mandatoryCat,logsum_trip_Potential_INEXUS,actEndTime,actEndType,actStartTime,actStartType,cost_BEAM,distance_bike,distance_mode_choice,distance_privateCar,distance_ridehail,distance_transit,distance_travelling,distance_walking,duration_in_privateCar,duration_in_ridehail,duration_in_transit,duration_on_bike,duration_travelling,duration_walking,emissionBiodiesel,emissionDiesel,emissionElectricity,emissionFood,emissionGasoline,emission_marginal,fuelBiodiesel,fuelDiesel,fuelElectricity,fuelFood,fuelGasoline,fuel_marginal,fuel_not_Food,mode_choice_planned_BEAM,numPassengers,parkingType,reason,replanning_status,ride_hail_pooled,transit_bus,transit_cable_car,transit_rail,transit_subway,transit_tram,vehicleIds,year,duration_door_to_door,waitTime,mode_choice_actual_5,mode_choice_actual_6,trip_id,person_id,household_id,tour_id,primary_purpose_x,trip_count,purpose,trip_mode_AS_trips,tour_type,tour_category,start,end,duration,tour_mode_AS_tours,earning,person_sex,sex,edu,race,work_at_home,age,value_of_time,free_parking_at_work,num_mand,lcm_county_id,tenure_mover,hh_size,tenure,hh_cars,hh_income,hhsize,income_in_thousands,median_value_of_time,hh_value_of_time,home_is_urban,home_is_rural,auto_ownership,DRIVEALONEFREE,DRIVEALONEPAY,SHARED2FREE,SHARED2PAY,SHARED3FREE,SHARED3PAY,WALK,BIKE,WALK_LOC,WALK_LRF,WALK_EXP,WALK_HVY,WALK_COM,DRIVE_LOC,DRIVE_LRF,DRIVE_EXP,DRIVE_HVY,DRIVE_COM,TAXI,TNC_SINGLE,TNC_SHARED,income_quartiles,MedianQuartiles,alpha,socialCarbonCost,Social_INEXUS,Potential_INEXUS_in_dollar,Realized_INEXUS_in_dollar
0,1,577.000000,ridehail,price_fleetsize,0.250000,-2.464308,0.089552,-12.000000,240000.000000,Home_to_othmaint,1.500000,hov2_teleportation,None,-2.287766,29293.000000,Home,29476.000000,othmaint,0.000000,0.000000,4632.391000,4632.391000,0.000000,0.000000,4632.391000,0.000000,183.000000,0.000000,0.000000,0.000000,183.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,183.000000,0.000000,car,car,577,1,1735309,72,school,2,othmaint,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.531774,-999.532278,-2.464308,-2.464596,-999.530422,-999.530623,-16.712076,-1001.492550,-1000.459856,-1998.770467,-1998.770467,-1998.770467,-1998.770467,-1999.307149,-2997.409495,-2997.409495,-2997.409495,-2997.409495,-8.620419,-8.994502,-9.672722,4thQ,219000.000000,0.100000,0.000000,-24.643081,-22.877665,-24.643081
1,1,577.000000,ridehail,price_fleetsize,0.250000,-2.259611,0.494786,23.000000,240000.000000,Home_to_othmaint,2.500000,hov2_teleportation,None,-1.882533,29361.000000,Home,29579.000000,othmaint,0.000000,0.000000,5382.075000,5382.075000,0.000000,0.000000,5382.075000,0.000000,218.000000,0.000000,0.000000,0.000000,218.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,218.000000,0.000000,car,car,577,1,1735309,72,school,2,othmaint,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.327077,-999.327369,-2.259611,-2.259778,-999.325724,-999.325841,-10.268612,-1000.848204,-1000.459856,-1998.770467,-1998.770467,-1998.770467,-1998.770467,-1999.307149,-2997.409495,-2997.409495,-2997.409495,-2997.409495,-8.111640,-9.024152,-11.861608,4thQ,219000.000000,0.100000,0.000000,-22.596107,-18.825330,-22.596107
2,1,577.000000,baseline,default,1.000000,-2.554453,0.000000,0.000000,240000.000000,Home_to_othmaint,1.000000,hov2_teleportation,None,-2.377319,31052.000000,Home,31247.000000,othmaint,0.000000,0.000000,4940.606000,4940.606000,0.000000,0.000000,4940.606000,0.000000,195.000000,0.000000,0.000000,0.000000,195.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,195.000000,0.000000,car,car,577,1,1735309,72,school,2,othmaint,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.621919,-999.622345,-2.554453,-2.554696,-999.620566,-999.620737,-38.227666,-1007.088933,-1000.459856,-1998.770467,-1998.770467,-1998.770467,-1998.770467,-1999.307149,-2997.409495,-2997.409495,-2997.409495,-2997.409495,-8.625908,-8.611274,-9.231232,4thQ,219000.000000,0.100000,0.000000,-25.544526,-23.773188,-25.544526
3,1,578.000000,ridehail,price_fleetsize,0.250000,-2.565106,-0.192297,7.000000,240000.000000,othmaint_to_school,1.500000,hov2_teleportation,None,-2.388670,29721.000000,othmaint,30046.000000,school,0.000000,0.000000,7476.099000,7476.099000,0.000000,0.000000,7476.099000,0.000000,325.000000,0.000000,0.000000,0.000000,325.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,325.000000,0.000000,car,car,578,1,1735309,72,school,2,school,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.632572,-999.633014,-2.565106,-2.565359,-999.631219,-999.631396,-17.437424,-1001.567111,-1001.491351,-1998.772718,-1999.043718,-1998.772718,-1998.772718,-1999.302789,-2997.411746,-2997.411746,-2997.411746,-2997.411746,-8.764279,-9.207617,-9.927299,4thQ,219000.000000,0.100000,0.000000,-25.651057,-23.886696,-25.651057
4,1,578.000000,ridehail,price_fleetsize,0.250000,-2.102836,0.292889,-17.000000,240000.000000,othmaint_to_school,2.500000,hov2_teleportation,None,-1.903483,29763.000000,othmaint,30064.000000,school,0.000000,0.000000,7678.068000,7678.068000,0.000000,0.000000,7678.068000,0.000000,301.000000,0.000000,0.000000,0.000000,301.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov2_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,301.000000,0.000000,car,car,578,1,1735309,72,school,2,school,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1,1.000000,asian,0,3,19.798008,False,1,6085,own not recent,four or more,1,two or more,gt150,4,240.000000,12.860000,29.682171,False,False,2,-999.170302,-999.170803,-2.102836,-2.103123,-999.168950,-999.169150,-15.367260,-1001.360095,-1001.491351,-1998.772718,-1999.043718,-1998.772718,-1998.772718,-1999.302789,-2997.411746,-2997.411746,-2997.411746,-2997.411746,-8.059820,-8.797988,-9.175784,4thQ,219000.000000,0.100000,0.000000,-21.028360,-19.034829,-21.028360

In [ ]:
%%time
sf_stacked.to_csv('s3://beam-core-act/deepDive/CleanData/SanFrancisco/Stacked/sf_2018_stacked_rh_price_fleetsz_0p25.csv', index=False)