In [1]:
import os
import os.path as op
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
%matplotlib inline
import seaborn as sns
sns.set_theme(style="darkgrid", color_codes=True)
sns.set(font_scale=1.35, style="ticks") #set styling preferences
import statsmodels.api as sm
from scipy import stats
import math
from math import pi
from pandas.api.types import is_string_dtype
from pandas.api.types import is_numeric_dtype
from scipy.spatial.distance import cdist
from scipy.cluster.vq import kmeans2,vq, whiten

In [2]:
# Show all columns and rows
pd.options.display.max_columns = None
pd.options.display.max_rows = None

#### Baseline

In [3]:
%%time
baseline2018 = "https://beam-core-act.s3.amazonaws.com/deepDive/CleanData/SanFrancisco/Baseline/"
sfbase = pd.read_csv(baseline2018 + 'sf_2018_base_utilities.csv')

<timed exec>:2: DtypeWarning: Columns (40) have mixed types. Specify dtype option on import or set low_memory=False.

CPU times: total: 1min 22s
Wall time: 5min 3s

In [4]:
# Showing the entire number in dataframe
pd.set_option('float_format', '{:f}'.format)

In [5]:
describe = sfbase.describe()

In [7]:
describe

,IDMerged,tripIndex,BlockGroupEnd,BlockGroupStart,actEndTime,actStartTime,cost_BEAM,distance_bike,distance_mode_choice,distance_privateCar,distance_ridehail,distance_transit,distance_travelling,distance_walking,duration_in_privateCar,duration_in_ridehail,duration_in_transit,duration_on_bike,duration_travelling,duration_walking,emissionBiodiesel,emissionDiesel,emissionElectricity,emissionFood,emissionGasoline,emission_marginal,fuelBiodiesel,fuelDiesel,fuelElectricity,fuelFood,fuelGasoline,fuel_marginal,fuel_not_Food,replanning_status,ride_hail_pooled,transit_bus,transit_cable_car,transit_rail,transit_subway,transit_tram,year,duration_door_to_door,waitTime,trip_id,person_id,household_id,tour_id,trip_num,trip_count,destination_x,origin_x,destination_logsum_x,depart,logsum_trip_mode_AS_trips,tour_type_count,tour_type_num,tour_num,tour_count,number_of_participants,destination_y,origin_y,household_id_x,tdd,start,end,duration,destination_logsum_y,logsum_tours_mode_AS_tours,parent_tour_id,earning,worker,student,hispanic.1,PNUM,sex,household_id_y,hours,MAR,edu,school_zone_id,race_id,work_at_home,age,work_zone_id,relate,hispanic,TAZ_x,ptype,pemploy,pstudent,home_x,home_y,school_segment,home_taz,value_of_time,school_taz,distance_to_school,roundtrip_auto_time_to_school,workplace_taz,workplace_location_logsum,distance_to_work,work_taz_area_type,roundtrip_auto_time_to_work,work_auto_savings,work_auto_savings_ratio,num_mand,num_work_tours,num_joint_tours,non_mandatory_tour_frequency,num_non_mand,num_escort_tours,num_eatout_tours,num_shop_tours,num_maint_tours,num_discr_tours,num_social_tours,num_non_escort_tours,gt55,seniors,VEHICL,lcm_county_id,block_id,gt2,age_of_head,race_of_head,tenure,income,serialno,num_workers,recent_mover,hispanic_status_of_head,hhsize,hh_type,TAZ_y,HHT,sample_rate,chunk_id,income_in_thousands,income_segment,median_value_of_time,hh_value_of_time,num_non_workers,num_drivers,num_adults,num_children,num_young_children,num_children_5_to_15,num_children_16_to_17,num_college_age,num_young_adults,auto_ownership,hh_work_auto_savings_ratio,num_under16_not_at_school,num_travel_active,num_travel_active_adults,num_travel_active_preschoolers,num_travel_active_children,num_travel_active_non_preschoolers,num_hh_joint_tours,SERIALNO,SPORDER,AGEP,SEX,DIS,HINCP,VEH,JWMNP,JWRIP,JWTR,RAC1P,RAC2P05,DRIVEALONEFREE,DRIVEALONEPAY,SHARED2FREE,SHARED2PAY,SHARED3FREE,SHARED3PAY,WALK,BIKE,WALK_LOC,WALK_LRF,WALK_EXP,WALK_HVY,WALK_COM,DRIVE_LOC,DRIVE_LRF,DRIVE_EXP,DRIVE_HVY,DRIVE_COM,TAXI,TNC_SINGLE,TNC_SHARED
count,2568424.000000,2568424.000000,2568117.000000,2568317.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2568424.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,494533.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,1160460.000000,2284813.000000,176978.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,621488.000000,2284813.000000,2284813.000000,1221547.000000,1221547.000000,1221547.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,1119979.000000,926167.000000,1187872.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000,2284813.000000
mean,3684550.168916,1208532683.379111,60547700678.825897,60547529326.821907,50580.672923,52203.101712,1.553038,69.938228,11671.586135,9731.332819,522.460794,659.237840,12179.578376,1196.608693,480.930151,27.506606,83.334865,13.987648,1530.147673,924.388403,0.000191,0.000504,0.000001,0.000000,0.000979,0.000003,2262154.820137,5950532.234991,6002.780884,47521.147518,13248925.066820,13312595.556401,21464423.961458,0.003800,0.002492,0.864694,0.010101,0.003059,0.060069,0.068711,2018.000000,1622.428789,92.281116,1208716932.182972,3685111.891265,1453599.483079,151089616.108401,1.234297,1.520506,737.094083,737.763042,10.833943,13.162214,-0.632397,1.136053,1.067462,1.193750,1.413696,1.025139,725.607429,753.915931,1453599.483079,87.655019,10.344115,15.849841,5.505726,13.243046,-0.842976,150957091.098815,37344.642303,0.534638,0.238820,0.206615,2.122255,1.519939,1453599.483079,22.394836,2.894427,16.556018,206.522610,3.145951,0.029715,40.202396,365.613867,2.017614,0.206615,757.737118,3.107318,2.080674,2.554002,-122.166870,37.730072,0.502242,757.737118,9.640889,206.786095,4.431205,11.193102,365.240104,13.253423,12.185240,2.770674,31.031478,190.936178,0.387189,0.700440,0.500897,0.059779,12.975385,0.951013,0.267716,0.087309,0.249579,0.133457,0.195657,0.052535,0.683296,0.345691,0.271285,2.190279,6054.027201,60543921366359.820312,0.887977,49.288353,2.972471,1.399159,120852.050158,2011028847855.389160,1.563268,0.175965,0.185300,3.391913,4.718282,757.737118,3.663932,0.097000,137369.061822,120.853989,3.008885,10.660840,10.232862,1.828645,2.538441,2.427576,0.964337,0.296176,0.613144,0.110865,0.304029,0.458562,2.191093,1.142155,0.176547,3.189246,2.284574,0.267019,0.904672,2.922227,0.085291,2011028847855.389160,2.122255,40.202396,1.519939,1.913714,120852.050158,2.139335,28.023800,1.193433,2.327641,3.145951,7.551235,-420.458706,-425.591221,-505.124371,-510.251531,-687.154140,-692.279158,-30.673153,-1068.045645,-1101.157818,-1858.539400,-1830.548021,-1874.215870,-1883.190028,-1874.979399,-2152.752440,-2152.899226,-2153.097730,-2153.229134,-14.000018,-13.158396,-11.216605
std,2133368.519885,699744874.411438,376884550.556146,376779423.001238,17143.336118,17506.279534,2.964236,748.607533,14003.543942,13705.870003,3216.967278,3742.314976,14200.832371,3559.014423,604.764094,154.284209,406.929456,149.721422,2703.636432,2616.902465,0.002082,0.003323,0.000034,0.000000,0.001550,0.000111,24593693.378309,39261404.890063,255559.781117,84134.253316,20970674.303551,20791095.277175,49311691.890287,0.093202,0.081521,4.403719,0.350105,0.133069,0.654974,0.865635,0.000000,2731.029941,312.136231,699710896.490754,2133264.928678,834835.800043,87463862.061260,0.549820,0.827479,421.358819,421.292485,3.808748,4.599412,1.401238,0.389939,0.272544,0.522370,0.794963,0.217606,424.933713,416.681129,834835.800043,47.409576,3.944912,3.679179,4.532946,2.421670,1.487355,87169407.829352,63515.792752,0.498799,0.426363,0.404877,1.356597,0.499602,834835.800043,21.079001,1.872782,6.191993,398.905709,2.831535,0.169800,20.961145,466.581062,3.382219,0.404877,415.255110,2.341953,1.201391,0.771403,0.272691,0.337042,0.952103,415.255110,9.128772,399.479617,6.428358,30.730182,466.634068,0.956851,11.805573,1.476452,50.370526,379.900126,0.449635,0.540369,0.541250,0.239086,20.868792,1.130897,0.649102,0.286137,0.489628,0.381538,0.443364,0.244779,0.876559,0.475593,0.616250,0.965924,37.778732,377701561422.339050,0.315394,14.552719,2.719149,0.489726,109081.992102,1414868741.600198,1.060486,0.380791,0.388541,1.787344,1.910912,415.255110,0.946183,0.000000,79294.022267,109.079777,1.090613,2.412183,9.511882,1.537872,1.253938,1.185806,1.179971,0.619923,0.919809,0.331689,0.663169,0.793847,0.965533,0.924593,0.501197,1.599489,1.078496,0.579913,1.105618,1.456878,0.283089,1414868741.600198,1.356597,20.961145,0.499602,0.280786,109081.992102,1.167554,21.491807,0.657498,3.066587,2.831535,23.716008,622.718174,625.104684,499.612533,505.657147,462.282989,468.896940,64.397229,295.496853,551.727027,414.180532,498.478371,358.607509,322.285555,580.137284,366.768867,367.120059,366.788124,365.678018,14.250034,13.673255,12.349572
min,1.000000,577.000000,60014001001.000000,60014001001.000000,18000.000000,18021.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2018.000000,0.000000,0.000000,577.000000,1.000000,14.000000,72.000000,1.000000,1.000000,1.000000,1.000000,-32.788409,5.000000,-77.670984,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,14.000000,0.000000,5.000000,5.000000,0.000000,-4.242697,-31.784351,121.000000,-7500.000000,0.000000,0.000000,0.000000,1.000000,1.000000,14.000000,0.000000,1.000000,0.000000,-1.000000,1.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,-123.523148,36.929681,0.000000,1.000000,0.667000,-1.000000,0.000001,0.000000,-1.000000,5.109579,0.000001,0.000000,0.000000,-1237.305900,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6001.000000,60014001001007.000000,0.000000,15.000000,1.000000,1.000000,-14600.000000,2009000000022.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.097000,0.000000,0.000000,1.000000,6.010000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2009000000022.000000,1.000000,0.000000,1.000000,1.000000,-14600.000000,0.000000,1.000000,1.000000,1.000000,1.000000,-9.000000,-3996.387714,-3997.208366,-2013.007192,-2997.008095,-1043.405192,-2016.527371,-1268.998495,-3017.267764,-2000.386770,-2009.577069,-2024.755705,-2011.577495,-2007.527733,-4002.101959,-4000.652758,-4002.227090,-4004.988641,-4000.850514,-366.099176,-445.635365,-212.800430
25%,1832351.000000,601011356.000000,60133200011.000000,60133200011.000000,35143.000000,36746.000000,0.000000,0.000000,3282.512750,427.577000,0.000000,0.000000,3510.689000,0.000000,29.000000,0.000000,0.000000,0.000000,402.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,68843.926000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2018.000000,449.000000,0.000000,600881225.000000,1831954.000000,722237.000000,75110153.000000,1.000000,1.000000,391.000000,392.000000,8.802748,9.000000,-1.148584,1.000000,1.000000,1.000000,1.000000,1.000000,378.000000,410.000000,722237.000000,48.000000,7.000000,13.000000,1.000000,11.976908,-1.461319,75276531.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,722237.000000,0.000000,1.000000,15.000000,-1.000000,1.000000,0.000000,24.000000,-1.000000,0.000000,0.000000,415.000000,1.000000,1.000000,2.000000,-122.397612,37.441931,0.000000,415.000000,3.631893,-1.000000,1.052649,0.000000,-1.000000,12.724620,3.446949,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,6013.000000,60133190002031.000000,1.000000,38.000000,1.000000,1.000000,49800.000000,2010000404287.000000,1.000000,0.000000,0.000000,2.000000,3.000000,415.000000,4.000000,0.097000,68675.000000,49.800000,2.000000,8.810000,3.923325,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.447191,0.000000,2.000000,2.000000,0.000000,0.000000,2.000000,0.000000,2010000404287.000000,1.000000,24.000000,1.000000,2.000000,49800.000000,1.000000,15.000000,1.000000,1.000000,1.000000,-9.000000,-999.466188,-999.488179,-999.713312,-999.727089,-999.939342,-999.949315,-35.253073,-1013.494320,-1002.411728,-1998.632682,-1999.874232,-1998.633923,-1998.627296,-1998.431078,-1998.428016,-1999.376394,-1998.431003,-1998.426128,-14.281089,-13.503941,-11.126851
50%,3680317.000000,1207144177.500000,60750311005.000000,60750311003.000000,51526.000000,52954.000000,0.560980,0.000000,6663.910000,5029.461500,0.000000,0.000000,7153.801000,243.905000,304.000000,0.000000,0.000000,0.000000,873.000000,201.000000,0.000000,0.000000,0.000000,0.000000,0.000421,0.000000,0.000000,0.000000,0.000000,12287.891000,5693584.251892,5817084.069413,7618739.992785,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2018.000000,936.000000,0.000000,1207535029.000000,3681509.000000,1493361.000000,150941878.000000,1.000000,1.000000,737.000000,737.000000,11.351722,13.000000,-0.401329,1.000000,1.000000,1.000000,1.000000,1.000000,729.000000,754.000000,1493361.000000,76.000000,9.000000,16.000000,5.000000,12.791220,-0.675189,150879260.000000,10000.000000,1.000000,0.000000,0.000000,2.000000,2.000000,1493361.000000,25.000000,3.000000,19.000000,-1.000000,1.000000,0.000000,41.000000,41.000000,1.000000,0.000000,758.000000,3.000000,1.000000,3.000000,-122.137374,37.733241,0.000000,758.000000,6.677189,-1.000000,2.501746,0.000000,39.000000,13.452963,8.232120,3.000000,13.410317,10.816666,0.090139,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,6075.000000,60750313013004.000000,1.000000,49.000000,1.000000,1.000000,93350.000000,2011000809598.000000,1.000000,0.000000,0.000000,3.000000,4.000000,758.000000,4.000000,0.097000,137389.000000,93.350000,3.000000,10.440000,7.158998,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,0.000000,3.000000,2.000000,0.000000,0.000000,3.000000,0.000000,2011000809598.000000,2.000000,41.000000,2.000000,2.000000,93350.000000,2.000000,20.000000,1.000000,1.000000,1.000000,1.000000,-1.185351,-1.207458,-999.033683,-999.057182,-999.409356,-999.413737,-14.291321,-1001.341689,-1000.788676,-1998.384124,-1999.222820,-1998.384313,-1998.380315,-1998.337496,-1998.387579,-1998.428883,-1998.402556,-1998.353995,-10.509320,-10.225349,-9.317984
75%,5524931.000000,1812177690.000000,60855054012.000000,60855053042.000000,64173.000000,65760.000000,1.883866,0.000000,14300.589000,12301.327500,0.000000,0.000000,15112.999250,1225.921500,634.000000,0.000000,0.000000,0.000000,1791.000000,976.000000,0.000000,0.000000,0.000000,0.000000,0.001220,0.000000,0.000000,0.000000,0.000000,60493.193000,16508954.413393,16629124.974358,21750665.537826,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2018.000000,1922.000000,0.000000,1812276101.000000,5525232.000000,2159464.000000,226534512.000000,1.000000,2.000000,1121.000000,1121.000000,13.282135,17.000000,0.132448,1.000000,1.000000,1.000000,2.000000,1.000000,1113.000000,1133.000000,2159464.000000,125.000000,13.000000,18.000000,10.000000,13.741923,-0.071104,225917378.000000,52000.000000,1.000000,0.000000,0.000000,3.000000,2.000000,2159464.000000,40.000000,5.000000,21.000000,169.000000,6.000000,0.000000,56.000000,724.000000,2.000000,0.000000,1136.000000,5.000000,3.000000,3.000000,-121.956311,37.936914,1.000000,1136.000000,12.214645,168.000000,5.149115,10.173790,722.000000,13.922723,17.332417,4.000000,44.900000,147.624980,1.000000,1.000000,1.000000,0.000000,16.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,3.000000,6085.000000,60855061013014.000000,1.000000,59.000000,6.000000,2.000000,155000.000000,2012001170491.000000,2.000000,0.000000,0.000000,4.000000,7.000000,1136.000000,4.000000,0.097000,205925.000000,155.000000,4.000000,12.860000,12.982101,3.000000,3.000000,3.000000,2.000000,0.000000,1.000000,0.000000,0.000000,1.000000,3.000000,1.799218,0.000000,4.000000,3.000000,0.000000,2.000000,4.000000,0.000000,2012001170491.000000,3.000000,56.000000,2.000000,2.000000,155000.000000,3.000000,35.000000,1.000000,1.000000,6.000000,1.000000,-0.533838,-0.541087,-1.590832,-1.608032,-5.232491,-5.267903,-5.092619,-1000.195537,-1000.049255,-1998.301370,-1998.634465,-1998.267887,-1998.238321,-1998.218431,-1998.324548,-1998.335665,-1998.326486,-1998.322262,-8.307355,-8.085336,-8.090172
max,7399583.000000,2427063454.000000,60971543043.000000,60971543043.000000,215257.000000,215782.000000,109.494682,53677.555000,424144.919878,184298.294000,151714.922000,125030.592620,340422.120697,186995.742894,8435.000000,6121.000000,10680.000000,10736.000000,135504.000000,135504.000000,0.121736,0.177223,0.006073,0.000000,0.036565,0.017446,1438310483.119500,2093882418.561200,46163368.103087,1910277.940000,494708255.035200,295807264.290039,2093882418.561200,3.000000,4.000000,139.000000,28.000000,21.000000,25.000000,40.000000,2018.000000,135504.000000,11134.000000,2427063454.000000,7399583.000000,2895003.000000,303382931.000000,4.000000,4.000000,1454.000000,1454.000000,25.743910,23.000000,2.858406,3.000000,3.000000,8.000000,8.000000,10.000000,1454.000000,1454.000000,2895003.000000,189.000000,23.000000,23.000000,18.000000,21.227001,21.434324,303372979.000000,729000.000000,1.000000,1.000000,1.000000,19.000000,2.000000,2895003.000000,99.000000,5.000000,24.000000,1454.000000,9.000000,1.000000,94.000000,1454.000000,15.000000,1.000000,1454.000000,8.000000,4.000000,3.000000,-121.268358,38.853940,3.000000,1454.000000,50.000000,1454.000000,126.423965,1637.033300,1454.000000,16.562170,122.746080,5.000000,1637.033300,4907.875000,1.000000,2.000000,2.000000,2.000000,92.000000,8.000000,3.000000,2.000000,3.000000,4.000000,3.000000,3.000000,8.000000,1.000000,19.000000,4.000000,6097.000000,60971543043142.000000,1.000000,94.000000,9.000000,2.000000,1354000.000000,2013001492566.000000,13.000000,1.000000,1.000000,20.000000,8.000000,1454.000000,4.000000,0.097000,274782.000000,1354.000000,4.000000,12.860000,50.000000,20.000000,20.000000,20.000000,10.000000,5.000000,8.000000,3.000000,11.000000,6.000000,4.000000,12.502062,8.000000,16.000000,16.000000,5.000000,8.000000,16.000000,2.000000,2013001492566.000000,19.000000,94.000000,2.000000,2.000000,1354000.000000,6.000000,173.000000,10.000000,12.000000,9.000000,67.000000,-0.000022,-0.000069,2.281199,2.278587,2.412730,2.409596,2.119035,0.764700,0.614336,0.923372,1.290403,0.811189,0.205978,-0.328825,-0.032547,-0.172657,0.254286,-0.335033,3.172714,3.752172,3.089220

In [15]:
sfbase.head()

,IDMerged,tripIndex,BlockGroupEnd,BlockGroupStart,actEndTime,actEndType,actStartTime,actStartType,cost_BEAM,distance_bike,distance_mode_choice,distance_privateCar,distance_ridehail,distance_transit,distance_travelling,distance_walking,duration_in_privateCar,duration_in_ridehail,duration_in_transit,duration_on_bike,duration_travelling,duration_walking,emissionBiodiesel,emissionDiesel,emissionElectricity,emissionFood,emissionGasoline,emission_marginal,fuelBiodiesel,fuelDiesel,fuelElectricity,fuelFood,fuelGasoline,fuel_marginal,fuel_not_Food,vehicleIds_estimate,mode_choice_actual_BEAM,mode_choice_planned_BEAM,numPassengers,parkingType,reason,replanning_status,ride_hail_pooled,scenario,transit_bus,transit_cable_car,transit_rail,transit_subway,transit_tram,vehicleIds,year,duration_door_to_door,waitTime,actPurpose,mode_choice_actual_5,trip_id,person_id,household_id,tour_id,primary_purpose_x,trip_num,outbound,trip_count,purpose,destination_x,origin_x,destination_logsum_x,depart,trip_mode_AS_trips,logsum_trip_mode_AS_trips,tour_type,tour_type_count,tour_type_num,tour_num,tour_count,tour_category,number_of_participants,destination_y,origin_y,household_id_x,tdd,start,end,duration,composition,destination_logsum_y,tour_mode_AS_tours,logsum_tours_mode_AS_tours,atwork_subtour_frequency,parent_tour_id,stop_frequency,primary_purpose_y,earning,worker,student,hispanic.1,person_sex,PNUM,sex,household_id_y,hours,MAR,person_age,edu,school_zone_id,race_id,race,work_at_home,age,work_zone_id,p_hispanic,relate,hispanic,TAZ_x,ptype,pemploy,pstudent,home_x,home_y,age_16_to_19,age_16_p,adult,male,female,has_non_worker,has_retiree,has_preschool_kid,has_driving_kid,has_school_kid,has_full_time,has_part_time,has_university,student_is_employed,nonstudent_to_school,is_student,is_gradeschool,is_highschool,is_university,school_segment,is_worker,home_taz,value_of_time,school_taz,distance_to_school,roundtrip_auto_time_to_school,workplace_taz,workplace_location_logsum,distance_to_work,workplace_in_cbd,work_taz_area_type,roundtrip_auto_time_to_work,work_auto_savings,work_auto_savings_ratio,free_parking_at_work,cdap_activity,travel_active,under16_not_at_school,has_preschool_kid_at_home,has_school_kid_at_home,mandatory_tour_frequency,work_and_school_and_worker,work_and_school_and_student,num_mand,num_work_tours,num_joint_tours,non_mandatory_tour_frequency,num_non_mand,num_escort_tours,num_eatout_tours,num_shop_tours,num_maint_tours,num_discr_tours,num_social_tours,num_non_escort_tours,gt55,seniors,VEHICL,lcm_county_id,hh_children,block_id,gt2,hispanic_head,age_of_head,race_of_head,tenure_mover,hh_size,sf_detached,tenure,hh_cars,income,hh_age_of_head,serialno,num_workers,hh_race_of_head,hh_income,recent_mover,hh_workers,hispanic_status_of_head,hh_seniors,hhsize,hh_type,TAZ_y,HHT,sample_rate,chunk_id,income_in_thousands,income_segment,median_value_of_time,hh_value_of_time,num_non_workers,num_drivers,num_adults,num_children,num_young_children,num_children_5_to_15,num_children_16_to_17,num_college_age,num_young_adults,non_family,family,home_is_urban,home_is_rural,auto_ownership,hh_work_auto_savings_ratio,num_under16_not_at_school,num_travel_active,num_travel_active_adults,num_travel_active_preschoolers,num_travel_active_children,num_travel_active_non_preschoolers,participates_in_jtf_model,joint_tour_frequency,num_hh_joint_tours,SERIALNO,SPORDER,AGEP,SEX,DIS,HINCP,VEH,JWMNP,JWRIP,JWTR,RAC1P,RAC2P05,DRIVEALONEFREE,DRIVEALONEPAY,SHARED2FREE,SHARED2PAY,SHARED3FREE,SHARED3PAY,WALK,BIKE,WALK_LOC,WALK_LRF,WALK_EXP,WALK_HVY,WALK_COM,DRIVE_LOC,DRIVE_LRF,DRIVE_EXP,DRIVE_HVY,DRIVE_COM,TAXI,TNC_SINGLE,TNC_SHARED
0,1,577.000000,60855042021.000000,60855035091.000000,29037.000000,Home,29601.000000,othmaint,0.000000,0.000000,6498.758000,6498.758000,0.000000,0.000000,6498.758000,0.000000,564.000000,0.000000,0.000000,0.000000,564.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,"body-1,teleportationSharedVehicle-1-1,body-1",hov3_teleportation,hov3_teleportation,NaN,NaN,NaN,0,0,baseline,0,0,0,0,0,NaN,2018,564.000000,0.000000,Home_to_othmaint,car,577.000000,1.000000,1735309.000000,72.000000,school,1.000000,True,2.000000,othmaint,595.000000,641.000000,5.730384,8.000000,SHARED2FREE,-2.150332,school,1.000000,1.000000,1.000000,1.000000,mandatory,1.000000,633.000000,641.000000,1735309.000000,60.000000,8.000000,14.000000,6.000000,NaN,NaN,SHARED2PAY,-1.011892,NaN,NaN,1out_0in,school,0.000000,0.000000,1.000000,0.000000,male,3.000000,1.000000,1735309.000000,0.000000,5.000000,19 and under,1.000000,633.000000,6.000000,asian,0.000000,3.000000,-1.000000,no,2.000000,0.000000,641.000000,8.000000,4.000000,1.000000,-121.806440,37.350304,False,False,False,True,False,False,False,True,False,False,True,False,False,False,False,True,True,False,False,1.000000,False,641.000000,19.798008,633.000000,1.986545,115.308334,-1.000000,NaN,NaN,False,NaN,0.000000,0.000000,0.000000,False,M,True,False,False,False,school1,False,False,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,6085.000000,yes,60855035091006.000000,1.000000,no,35.000000,6.000000,own not recent,four or more,yes,1.000000,two or more,240000.000000,gt35-lt65,2010000482865.000000,2.000000,asian,gt150,0.000000,two or more,0.000000,no,4.000000,3.000000,641.000000,4.000000,0.097000,60138.000000,240.000000,4.000000,12.860000,29.682171,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,1.000000,True,False,False,False,2.000000,1.403117,0.000000,4.000000,2.000000,2.000000,2.000000,2.000000,True,0_tours,0.000000,2010000482865.000000,3.000000,3.000000,1.000000,2.000000,240000.000000,2.000000,NaN,NaN,NaN,6.000000,40.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.828240
1,1,578.000000,60855042021.000000,60855042022.000000,29751.000000,othmaint,29890.000000,school,0.000000,0.000000,1641.981000,1641.981000,0.000000,0.000000,1641.981000,0.000000,139.000000,0.000000,0.000000,0.000000,139.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,"body-1,teleportationSharedVehicle-2-1,body-1",hov3_teleportation,hov3_teleportation,NaN,NaN,NaN,0,0,baseline,0,0,0,0,0,NaN,2018,139.000000,0.000000,othmaint_to_school,car,578.000000,1.000000,1735309.000000,72.000000,school,2.000000,True,2.000000,school,633.000000,595.000000,NaN,8.000000,SHARED2FREE,-2.020166,school,1.000000,1.000000,1.000000,1.000000,mandatory,1.000000,633.000000,641.000000,1735309.000000,60.000000,8.000000,14.000000,6.000000,NaN,NaN,SHARED2PAY,-1.011892,NaN,NaN,1out_0in,school,0.000000,0.000000,1.000000,0.000000,male,3.000000,1.000000,1735309.000000,0.000000,5.000000,19 and under,1.000000,633.000000,6.000000,asian,0.000000,3.000000,-1.000000,no,2.000000,0.000000,641.000000,8.000000,4.000000,1.000000,-121.806440,37.350304,False,False,False,True,False,False,False,True,False,False,True,False,False,False,False,True,True,False,False,1.000000,False,641.000000,19.798008,633.000000,1.986545,115.308334,-1.000000,NaN,NaN,False,NaN,0.000000,0.000000,0.000000,False,M,True,False,False,False,school1,False,False,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,6085.000000,yes,60855035091006.000000,1.000000,no,35.000000,6.000000,own not recent,four or more,yes,1.000000,two or more,240000.000000,gt35-lt65,2010000482865.000000,2.000000,asian,gt150,0.000000,two or more,0.000000,no,4.000000,3.000000,641.000000,4.000000,0.097000,60138.000000,240.000000,4.000000,12.860000,29.682171,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,1.000000,True,False,False,False,2.000000,1.403117,0.000000,4.000000,2.000000,2.000000,2.000000,2.000000,True,0_tours,0.000000,2010000482865.000000,3.000000,3.000000,1.000000,2.000000,240000.000000,2.000000,NaN,NaN,NaN,6.000000,40.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1998.779651,-1998.779651,-1999.050651,-1998.779651,-1998.779651,-1999.528158,-2997.418679,-2998.777234,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.958320
2,1,581.000000,60855033222.000000,60855042022.000000,52812.000000,school,53394.000000,Home,0.000000,0.000000,6326.206000,6326.206000,0.000000,0.000000,6326.206000,0.000000,582.000000,0.000000,0.000000,0.000000,582.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,"body-1,teleportationSharedVehicle-3-1,body-1",hov3_teleportation,hov3_teleportation,NaN,NaN,NaN,0,0,baseline,0,0,0,0,0,NaN,2018,582.000000,0.000000,school_to_Home,car,581.000000,1.000000,1735309.000000,72.000000,school,1.000000,False,1.000000,Home,641.000000,633.000000,NaN,14.000000,SHARED2FREE,-1.999284,school,1.000000,1.000000,1.000000,1.000000,mandatory,1.000000,633.000000,641.000000,1735309.000000,60.000000,8.000000,14.000000,6.000000,NaN,NaN,SHARED2PAY,-1.011892,NaN,NaN,1out_0in,school,0.000000,0.000000,1.000000,0.000000,male,3.000000,1.000000,1735309.000000,0.000000,5.000000,19 and under,1.000000,633.000000,6.000000,asian,0.000000,3.000000,-1.000000,no,2.000000,0.000000,641.000000,8.000000,4.000000,1.000000,-121.806440,37.350304,False,False,False,True,False,False,False,True,False,False,True,False,False,False,False,True,True,False,False,1.000000,False,641.000000,19.798008,633.000000,1.986545,115.308334,-1.000000,NaN,NaN,False,NaN,0.000000,0.000000,0.000000,False,M,True,False,False,False,school1,False,False,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,6085.000000,yes,60855035091006.000000,1.000000,no,35.000000,6.000000,own not recent,four or more,yes,1.000000,two or more,240000.000000,gt35-lt65,2010000482865.000000,2.000000,asian,gt150,0.000000,two or more,0.000000,no,4.000000,3.000000,641.000000,4.000000,0.097000,60138.000000,240.000000,4.000000,12.860000,29.682171,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,1.000000,True,False,False,False,2.000000,1.403117,0.000000,4.000000,2.000000,2.000000,2.000000,2.000000,True,0_tours,0.000000,2010000482865.000000,3.000000,3.000000,1.000000,2.000000,240000.000000,2.000000,NaN,NaN,NaN,6.000000,40.000000,-999.689724,-999.692354,-3.428142,-3.429645,-2.458329,-2.459381,-2.303144,-999.883016,-1000.424595,-1998.779651,-1999.424595,-1998.779651,-1998.779651,-2997.418679,-2997.418679,-2997.418679,-2997.418679,-2997.418679,-9.975599,-10.166096,-9.463768
3,2,689.000000,60855123082.000000,60855035091.000000,46533.000000,work,48475.000000,atwork,3.656274,0.000000,34122.434000,33336.011000,0.000000,0.000000,34122.434000,786.423000,1337.000000,0.000000,0.000000,0.000000,1942.000000,605.000000,0.000000,0.000000,0.000000,0.000000,0.003731,0.000000,0.000000,0.000000,0.000000,41680.419000,50479441.441098,50521121.860098,50479441.441098,"body-2,539168,539168,body-2",car,car,"1.0, 0.0, 0.0, 1.0","Public, Public",NaN,0,0,baseline,0,0,0,0,0,"539168, body-2",2018,1942.000000,0.000000,work_to_atwork,car,689.000000,2.000000,1735309.000000,86.000000,atwork,1.000000,True,1.000000,atwork,700.000000,700.000000,NaN,12.000000,DRIVEALONEFREE,-0.505729,eat,1.000000,1.000000,1.000000,1.000000,atwork,1.000000,700.000000,700.000000,1735309.000000,114.000000,12.000000,14.000000,2.000000,NaN,15.981749,DRIVEALONEFREE,-0.390809,NaN,121.000000,0out_0in,atwork,77000.000000,1.000000,0.000000,0.000000,female,2.000000,2.000000,1735309.000000,40.000000,1.000000,20 to 35,21.000000,-1.000000,6.000000,asian,0.000000,30.000000,700.000000,no,1.000000,0.000000,641.000000,1.000000,1.000000,3.000000,-121.806440,37.350304,False,True,True,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,0.000000,True,641.000000,29.682171,-1.000000,NaN,0.000000,700.000000,13.778423,17.631730,False,4.000000,73.050000,707.131200,1.000000,False,M,True,False,False,False,work1,False,False,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,6085.000000,yes,60855035091006.000000,1.000000,no,35.000000,6.000000,own not recent,four or more,yes,1.000000,two or more,240000.000000,gt35-lt65,2010000482865.000000,2.000000,asian,gt150,0.000000,two or more,0.000000,no,4.000000,3.000000,641.000000,4.000000,0.097000,60138.000000,240.000000,4.000000,12.860000,29.682171,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,1.000000,True,False,False,False,2.000000,1.403117,0.000000,4.000000,2.000000,2.000000,2.000000,2.000000,True,0_tours,0.000000,2010000482865.000000,2.000000,30.000000,2.000000,2.000000,240000.000000,2.000000,15.000000,1.000000,1.000000,6.000000,40.000000,-0.815910,-0.818141,-999.815910,-999.817185,-999.815910,-999.816802,-14.840951,-1999.742783,-1998.140532,-1998.140532,-1998.140532,-1998.140532,-1998.140532,-1998.308616,-1998.308616,-1998.308616,-1998.308616,-1998.308616,-10.575011,-10.203032,-9.792319
4,2,693.000000,60855123083.000000,60855123111.000000,49010.000000,atwork,49126.000000,work,0.182227,0.000000,1691.729000,1661.452000,0.000000,0.000000,1691.729000,30.277000,93.000000,0.000000,0.000000,0.000000,116.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000165,0.000000,0.000000,0.000000,0.000000,1604.681000,2238444.792429,2240049.473429,2238444.792429,"body-2,539168,539168,body-2",car,car,"1.0, 0.0, 0.0, 1.0","Public, Workplace",NaN,0,0,baseline,0,0,0,0,0,"539168, body-2",2018,116.000000,0.000000,atwork_to_work,car,693.000000,2.000000,1735309.000000,86.000000,atwork,1.000000,False,1.000000,Work,700.000000,700.000000,NaN,14.000000,DRIVEALONEPAY,-0.507800,eat,1.000000,1.000000,1.000000,1.000000,atwork,1.000000,700.000000,700.000000,1735309.000000,114.000000,12.000000,14.000000,2.000000,NaN,15.981749,DRIVEALONEFREE,-0.390809,NaN,121.000000,0out_0in,atwork,77000.000000,1.000000,0.000000,0.000000,female,2.000000,2.000000,1735309.000000,40.000000,1.000000,20 to 35,21.000000,-1.000000,6.000000,asian,0.000000,30.000000,700.000000,no,1.000000,0.000000,641.000000,1.000000,1.000000,3.000000,-121.806440,37.350304,False,True,True,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,0.000000,True,641.000000,29.682171,-1.000000,NaN,0.000000,700.000000,13.778423,17.631730,False,4.000000,73.050000,707.131200,1.000000,False,M,True,False,False,False,work1,False,False,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,6085.000000,yes,60855035091006.000000,1.000000,no,35.000000,6.000000,own not recent,four or more,yes,1.000000,two or more,240000.000000,gt35-lt65,2010000482865.000000,2.000000,asian,gt150,0.000000,two or more,0.000000,no,4.000000,3.000000,641.000000,4.000000,0.097000,60138.000000,240.000000,4.000000,12.860000,29.682171,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,1.000000,True,False,False,False,2.000000,1.403117,0.000000,4.000000,2.000000,2.000000,2.000000,2.000000,True,0_tours,0.000000,2010000482865.000000,2.000000,30.000000,2.000000,2.000000,240000.000000,2.000000,15.000000,1.000000,1.000000,6.000000,40.000000,-0.816950,-0.819181,-999.816504,-999.817779,-999.816326,-999.817218,-14.840951,-1999.742783,-1998.140532,-1998.140532,-1998.140532,-1998.140532,-1998.140532,-1998.308616,-1998.308616,-1998.308616,-1998.308616,-1998.308616,-10.575011,-10.203032,-9.792319

In [12]:
sfbase[sfbase.work_at_home == 1].shape

(67893, 266)

In [13]:
sfbase[sfbase.work_at_home == 0].shape

(2216920, 266)

In [14]:
sfbase[sfbase.work_at_home.isna()].shape

(283611, 266)

In [19]:
describe.to_csv('C:/Shared-Work/Data/CleanData/ASIM_BEAM_Merged/describe.csv')

#### Ridehail Scenarios

In [6]:
%%time
rh_flsz_175_path = "https://beam-core-act.s3.amazonaws.com/deepDive/CleanData/SanFrancisco/RideHail_FleetSize/"
sf_rh_flsz_175 = pd.read_csv(rh_flsz_175_path + 'sf_2018_rh_flsz_1p75_utilities.csv')

<timed exec>:2: DtypeWarning: Columns (40,61,84,88,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,139,148,153,155,156,157,158,160,161,218,219,220,221,230) have mixed types. Specify dtype option on import or set low_memory=False.

CPU times: total: 1min 22s
Wall time: 2min 24s

In [7]:
%%time
rh_flsz_025_path = "https://beam-core-act.s3.amazonaws.com/deepDive/CleanData/SanFrancisco/RideHail_FleetSize/"
sf_rh_flsz_025 = pd.read_csv(rh_flsz_025_path + 'sf_2018_rh_flsz_0p25_utilities.csv')

CPU times: total: 1min 18s
Wall time: 4min 12s

In [8]:
sfbase.shape

(2568424, 266)

In [9]:
sf_rh_flsz_025.shape

(2529260, 264)

In [10]:
sf_rh_flsz_175.shape

(2529288, 266)

In [11]:
sf_rh_flsz_175 = sf_rh_flsz_175.drop(['BlockGroupEnd','BlockGroupStart'], axis=1)

In [12]:
sfbase = sfbase.drop(['BlockGroupEnd','BlockGroupStart'], axis=1)

In [17]:
#sf_rh_flsz_175 = sf_rh_flsz_175.drop(sf_rh_flsz_175.columns[245:625], axis=1)

In [20]:
#sf_rh_flsz_175 = sf_rh_flsz_175.drop(sf_rh_flsz_175.columns[235:245], axis=1)

In [23]:
#sf_rh_flsz_175 = sf_rh_flsz_175.drop(sf_rh_flsz_175.columns[233:235], axis=1)

In [53]:
#sf_transit_fr_05 = sf_transit_fr_05.drop(['5','6','7','8','9','10','11'], axis=1)

In [30]:
frames = [sf_rh_flsz_025, sfbase, sf_rh_flsz_175]
sf_stacked = pd.concat(frames)

In [31]:
sf_stacked = sf_stacked.drop(['has_school_kid','has_preschool_kid','has_retiree','has_non_worker','adult','hispanic','relate',
                             'pstudent','pemploy','ptype','p_hispanic','age_16_p','age_16_to_19','work_zone_id',
                             'race_id','school_zone_id','person_age','MAR','hours','hispanic.1','student',
                             'worker','stop_frequency','composition','tdd','number_of_participants','tour_type_count',
                             'tour_type_num','tour_num','tour_count', 'outbound', 'trip_num','num_under16_not_at_school',
                             'family','non_family','num_young_adults','num_college_age','num_children_16_to_17',
                              'num_children_5_to_15','num_young_children'], axis=1)

In [32]:
sf_stacked = sf_stacked.drop(['vehicleIds_estimate','destination_x','origin_x','depart',
                             'origin_y', 'destination_y','parent_tour_id','atwork_subtour_frequency','household_id_y',
                              'TAZ_x','home_x','home_y','male','female', 'has_driving_kid','has_full_time','has_part_time',
                              'has_university','student_is_employed', 'nonstudent_to_school', 'is_student','is_gradeschool',
                              'is_gradeschool','is_highschool','is_university','school_segment','is_worker','home_taz',  
                             'school_taz','distance_to_school','roundtrip_auto_time_to_school','workplace_taz',
                              'distance_to_work','workplace_in_cbd', 'work_taz_area_type', 'hh_race_of_head',
                             'roundtrip_auto_time_to_work','work_auto_savings_ratio','cdap_activity', 'travel_active', 
                              'under16_not_at_school','has_preschool_kid_at_home', 'block_id','gt2','hispanic_head',
                             'has_school_kid_at_home','work_and_school_and_worker', 'age_of_head', 'race_of_head',
                              'work_and_school_and_student', 'VEHICL','hh_children','hh_age_of_head','num_workers',
                              'gt55','seniors', 'recent_mover', 'hh_workers', 'hispanic_status_of_head', 'hh_seniors', 
                             'hh_type', 'TAZ_y', 'HHT', 'sample_rate', 'chunk_id', 'income_segment', 'num_non_workers', 
                             'num_drivers', 'num_adults', 'num_children', 'hh_work_auto_savings_ratio', 'num_travel_active', 
                             'num_travel_active_adults','num_travel_active_preschoolers', 'num_travel_active_children', 
                              'num_travel_active_non_preschoolers', 'participates_in_jtf_model', 'joint_tour_frequency',
                              'num_hh_joint_tours', 'SERIALNO', 'HINCP', 'JWMNP', 'JWRIP', 'JWTR', 'RAC1P', 'RAC2P05'], axis=1)
#'BlockGroupEnd','BlockGroupStart'

In [33]:
sf_stacked = sf_stacked.drop(['serialno'], axis=1)

In [34]:
sf_stacked['lever'] = "default"

In [35]:
sf_stacked['lever'] = sf_stacked['lever'].astype("category")

In [36]:
sf_stacked['lever'] = np.where((sf_stacked['scenario'] == 'rhflsz0p25')|
                               (sf_stacked['scenario'] == 'rhflsz1p75'), 'fleet_size' , sf_stacked['lever'])

In [37]:
sf_stacked['lever_position'] = 1

In [38]:
sf_stacked['lever_position'] = np.where(sf_stacked['scenario'] == 'rhflsz0p25', 0.25 , sf_stacked['lever_position'])

In [39]:
sf_stacked['lever_position'] = np.where(sf_stacked['scenario'] == 'rhflsz1p75', 1.75 , sf_stacked['lever_position'])

In [54]:
sf_stacked['scenario'] = np.where(sf_stacked['scenario'] == 'rhflsz0p25', "ridehail" , sf_stacked['scenario'])

In [55]:
sf_stacked['scenario'] = np.where(sf_stacked['scenario'] == 'rhflsz1p75', "ridehail" , sf_stacked['scenario'])

In [ ]:
#%%time
#sf_stacked.to_csv('s3://beam-core-act/deepDive/CleanData/SanFrancisco/Stacked/sf_2018_stacked_tr_fr.csv', index=False)

#### Stacked File

In [3]:
%%time
stacked_tr_fr_path = "https://beam-core-act.s3.amazonaws.com/deepDive/CleanData/SanFrancisco/Stacked/"
sf_stacked_tr_fr = pd.read_csv(stacked_tr_fr_path + 'sf_2018_stacked_tr_fr.csv')

<timed exec>:2: DtypeWarning: Columns (37) have mixed types. Specify dtype option on import or set low_memory=False.

CPU times: total: 3min 46s
Wall time: 8min 2s

In [56]:
sf_stacked_rh_flsz = sf_stacked.sort_values(by=['IDMerged', 'tripIndex', 'lever_position']).reset_index(drop=True)

In [57]:
sf_stacked_rh_flsz.scenario.unique()

array(['ridehail', 'baseline'], dtype=object)

In [58]:
# shift column 'person' to first position
first_column = sf_stacked_rh_flsz.pop('scenario')
second_column = sf_stacked_rh_flsz.pop('lever')
third_column = sf_stacked_rh_flsz.pop('lever_position')
fourth_column = sf_stacked_rh_flsz.pop('logsum_trip_mode_AS_trips')
# insert column using insert(position,column_name,first_column) function
sf_stacked_rh_flsz.insert(2, 'scenario', first_column)
sf_stacked_rh_flsz.insert(3, 'lever', second_column)
sf_stacked_rh_flsz.insert(4, 'lever_position', third_column)
sf_stacked_rh_flsz.insert(5, 'logsum_trip_mode_AS_trips', fourth_column)

In [59]:
#sf_stacked_tr_fr['logsum_relative_to_baseline'] = sf_stacked_tr_fr.groupby(['IDMerged','tripIndex'])['logsum_trip_mode_AS_trips'].apply(lambda x: x.diff())

In [60]:
#sf_stacked_tr_fr['logsum_relative_to_baseline'] = sf_stacked_tr_fr['logsum_trip_mode_AS_trips'] - sf_stacked_tr_fr.loc[sf_stacked_tr_fr.groupby(['IDMerged','tripIndex'])['lever_position'].transform('idxmin'), 'logsum_trip_mode_AS_trips'].values

In [61]:
%%time
sf_stacked_rh_flsz['logsum_relative_to_baseline'] = sf_stacked_rh_flsz['logsum_trip_mode_AS_trips'] - (sf_stacked_rh_flsz['logsum_trip_mode_AS_trips'].where(sf_stacked_rh_flsz['lever_position'].eq(1.0))
                                                                                                  .groupby([sf_stacked_rh_flsz['IDMerged'],sf_stacked_rh_flsz['tripIndex']])
                                                                                                   .transform('first')
                                                                                                   .convert_dtypes())

CPU times: total: 2.41 s
Wall time: 3.01 s

In [62]:
sf_stacked_rh_flsz.head()

,IDMerged,tripIndex,scenario,lever,lever_position,logsum_trip_mode_AS_trips,actEndTime,actEndType,actStartTime,actStartType,cost_BEAM,distance_bike,distance_mode_choice,distance_privateCar,distance_ridehail,distance_transit,distance_travelling,distance_walking,duration_in_privateCar,duration_in_ridehail,duration_in_transit,duration_on_bike,duration_travelling,duration_walking,emissionBiodiesel,emissionDiesel,emissionElectricity,emissionFood,emissionGasoline,emission_marginal,fuelBiodiesel,fuelDiesel,fuelElectricity,fuelFood,fuelGasoline,fuel_marginal,fuel_not_Food,mode_choice_actual_BEAM,mode_choice_planned_BEAM,numPassengers,parkingType,reason,replanning_status,ride_hail_pooled,transit_bus,transit_cable_car,transit_rail,transit_subway,transit_tram,vehicleIds,year,duration_door_to_door,waitTime,actPurpose,mode_choice_actual_5,trip_id,person_id,household_id,tour_id,primary_purpose_x,trip_count,purpose,destination_logsum_x,trip_mode_AS_trips,tour_type,tour_category,household_id_x,start,end,duration,destination_logsum_y,tour_mode_AS_tours,logsum_tours_mode_AS_tours,primary_purpose_y,earning,person_sex,PNUM,sex,edu,race,work_at_home,age,value_of_time,workplace_location_logsum,work_auto_savings,free_parking_at_work,mandatory_tour_frequency,num_mand,num_work_tours,num_joint_tours,non_mandatory_tour_frequency,num_non_mand,num_escort_tours,num_eatout_tours,num_shop_tours,num_maint_tours,num_discr_tours,num_social_tours,num_non_escort_tours,lcm_county_id,tenure_mover,hh_size,sf_detached,tenure,hh_cars,income,hh_income,hhsize,income_in_thousands,median_value_of_time,hh_value_of_time,home_is_urban,home_is_rural,auto_ownership,SPORDER,AGEP,SEX,DIS,VEH,DRIVEALONEFREE,DRIVEALONEPAY,SHARED2FREE,SHARED2PAY,SHARED3FREE,SHARED3PAY,WALK,BIKE,WALK_LOC,WALK_LRF,WALK_EXP,WALK_HVY,WALK_COM,DRIVE_LOC,DRIVE_LRF,DRIVE_EXP,DRIVE_HVY,DRIVE_COM,TAXI,TNC_SINGLE,TNC_SHARED,logsum_relative_to_baseline
0,1,577.000000,ridehail,fleet_size,0.250000,-1.896507,29073.000000,Home,30450.000000,othmaint,0.000000,0.000000,16246.598000,16246.598000,0.000000,0.000000,16246.598000,0.000000,1377.000000,0.000000,0.000000,0.000000,1377.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,1377.000000,0.000000,Home_to_othmaint,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,5.940829,SHARED2FREE,school,mandatory,1735309.000000,8.000000,15.000000,7.000000,NaN,SHARED2PAY,-0.619711,school,0.000000,male,3.000000,1.000000,1.000000,asian,0.000000,3.000000,19.798008,NaN,0.000000,False,school1,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6085.000000,own not recent,four or more,yes,1.000000,two or more,240000.000000,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.866180,0.253825
1,1,577.000000,baseline,default,1.000000,-2.150332,29037.000000,Home,29601.000000,othmaint,0.000000,0.000000,6498.758000,6498.758000,0.000000,0.000000,6498.758000,0.000000,564.000000,0.000000,0.000000,0.000000,564.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,564.000000,0.000000,Home_to_othmaint,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,5.730384,SHARED2FREE,school,mandatory,1735309.000000,8.000000,14.000000,6.000000,NaN,SHARED2PAY,-1.011892,school,0.000000,male,3.000000,1.000000,1.000000,asian,0.000000,3.000000,19.798008,NaN,0.000000,False,school1,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6085.000000,own not recent,four or more,yes,1.000000,two or more,240000.000000,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.828240,0.000000
2,1,577.000000,ridehail,fleet_size,1.750000,-0.982639,29350.000000,Home,30727.000000,othmaint,0.000000,0.000000,16246.598000,16246.598000,0.000000,0.000000,16246.598000,0.000000,1377.000000,0.000000,0.000000,0.000000,1377.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,1377.000000,0.000000,Home_to_othmaint,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,7.640787,SHARED3PAY,school,mandatory,1735309.000000,8.000000,14.000000,6.000000,NaN,SHARED3PAY,0.206254,school,0.000000,male,3.000000,1.000000,1.000000,asian,0.000000,3.000000,19.798008,NaN,0.000000,False,school1,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6085.000000,own not recent,four or more,yes,1.000000,two or more,240000.000000,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,3.000000,1.000000,2.000000,2.000000,-999.445180,-999.446910,-3.185499,-3.186488,-2.216447,-2.217139,-2.388872,-999.925880,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-9.585779,-9.730563,-8.534333,1.167693
3,1,578.000000,ridehail,fleet_size,0.250000,-1.404211,31179.000000,othmaint,32131.000000,school,0.000000,0.000000,11389.821000,11389.821000,0.000000,0.000000,11389.821000,0.000000,952.000000,0.000000,0.000000,0.000000,952.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,952.000000,0.000000,othmaint_to_school,car,578.000000,1.000000,1735309.000000,72.000000,school,2.000000,school,NaN,SHARED2FREE,school,mandatory,1735309.000000,8.000000,15.000000,7.000000,NaN,SHARED2PAY,-0.619711,school,0.000000,male,3.000000,1.000000,1.000000,asian,0.000000,3.000000,19.798008,NaN,0.000000,False,school1,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6085.000000,own not recent,four or more,yes,1.000000,two or more,240000.000000,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,3.000000,1.000000,2.000000,2.000000,-999.203047,-999.203839,-2.943366,-2.943819,-1.974314,-1.974631,-1.962304,-999.712596,-1998.779651,-1998.779651,-1999.050651,-1998.779651,-1998.779651,-1999.528158,-2997.418679,-2998.777234,-2997.418679,-2997.418679,-9.202695,-9.493403,-8.148759,0.615956
4,1,578.000000,baseline,default,1.000000,-2.020166,29751.000000,othmaint,29890.000000,school,0.000000,0.000000,1641.981000,1641.981000,0.000000,0.000000,1641.981000,0.000000,139.000000,0.000000,0.000000,0.000000,139.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,139.000000,0.000000,othmaint_to_school,car,578.000000,1.000000,1735309.000000,72.000000,school,2.000000,school,NaN,SHARED2FREE,school,mandatory,1735309.000000,8.000000,14.000000,6.000000,NaN,SHARED2PAY,-1.011892,school,0.000000,male,3.000000,1.000000,1.000000,asian,0.000000,3.000000,19.798008,NaN,0.000000,False,school1,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6085.000000,own not recent,four or more,yes,1.000000,two or more,240000.000000,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1998.779651,-1998.779651,-1999.050651,-1998.779651,-1998.779651,-1999.528158,-2997.418679,-2998.777234,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.958320,0.000000

In [63]:
sf_stacked_rh_flsz['door_to_door_time_relative_to_baseline'] = sf_stacked_rh_flsz['duration_door_to_door'] - (sf_stacked_rh_flsz['duration_door_to_door'].where(sf_stacked_rh_flsz['lever_position'].eq(1.0))
                                                                                                  .groupby([sf_stacked_rh_flsz['IDMerged'],sf_stacked_rh_flsz['tripIndex']])
                                                                                                   .transform('first')
                                                                                                   .convert_dtypes())

In [64]:
# shift columns to first position
first_column = sf_stacked_rh_flsz.pop('logsum_relative_to_baseline')
second_column = sf_stacked_rh_flsz.pop('door_to_door_time_relative_to_baseline')
third_column = sf_stacked_rh_flsz.pop('income')
fourth_column = sf_stacked_rh_flsz.pop('actPurpose')
# insert column using insert(position,column_name,first_column) function
sf_stacked_rh_flsz.insert(5, 'logsum_relative_to_baseline', first_column)
sf_stacked_rh_flsz.insert(6, 'door_to_door_time_relative_to_baseline', second_column)
sf_stacked_rh_flsz.insert(7, 'income', third_column)
sf_stacked_rh_flsz.insert(8, 'actPurpose', fourth_column)

In [65]:
# Drop unused columns
sf_stacked_rh_flsz = sf_stacked_rh_flsz.drop(['sf_detached','destination_logsum_x',
                                          'household_id_x','destination_logsum_y','logsum_tours_mode_AS_tours','primary_purpose_y',
                                          'PNUM','workplace_location_logsum','work_auto_savings','mandatory_tour_frequency',
                                          'SPORDER'], axis=1)

In [13]:
# Rename to potential INEXUS
sf_stacked_tr_fr.rename(columns={"logsum_trip_mode_AS_trips":"logsum_trip_potential_INEXUS"}, inplace=True)

In [67]:
# Column with six summarized modes
conditions  = [(sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail') | (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_pooled'), 
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk_transit') | (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'drive_transit')|(sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'bike_transit'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk'), (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'bike'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car') | (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov2')| (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov3')|(sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov2_teleportation')| (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov3_teleportation'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_transit')]
choices = [ 'ride_hail', 'transit', 'walk', 'bike', 'car', 'ride_hail_transit']

In [69]:
sf_stacked_rh_flsz['mode_choice_actual_6'] = np.select(conditions, choices, default=np.nan)

In [70]:
# shift columns to first position
#first_column = sf_stacked_tr_fr.pop('mode_choice_actual_6')
second_column = sf_stacked_rh_flsz.pop('mode_choice_actual_BEAM')
#third_column = sf_stacked_tr_fr.pop('income')
#fourth_column = sf_stacked_tr_fr.pop('actPurpose')
# insert column using insert(position,column_name,first_column) function
#sf_stacked_tr_fr.insert(9, 'mode_choice_actual_6', first_column)
sf_stacked_rh_flsz.insert(10, 'mode_choice_actual_BEAM', second_column)
#sf_stacked_tr_fr.insert(11, 'income', third_column)
#sf_stacked_tr_fr.insert(12, 'actPurpose', fourth_column)

In [71]:
sf_stacked_rh_flsz[sf_stacked_rh_flsz['mode_choice_actual_6'] == 'ride_hail_transit'].shape

(1781, 132)

In [26]:
sf_stacked_tr_fr[sf_stacked_tr_fr['replanning_status'] > 0].shape

(24516, 132)

In [51]:
%%time
sf_stacked_tr_fr.to_csv('s3://beam-core-act/deepDive/CleanData/SanFrancisco/Stacked/sf_2018_stacked_tr_fr_v2.csv', index=False)

CPU times: total: 12min 32s
Wall time: 16min 43s

#### Stacked v2

In [18]:
%%time
stacked_tr_fr_path = "https://beam-core-act.s3.amazonaws.com/deepDive/CleanData/SanFrancisco/Stacked/"
sf_stacked_tr_fr = pd.read_csv(stacked_tr_fr_path + 'sf_2018_stacked_tr_fr_v2.csv')

CPU times: total: 3min 57s
Wall time: 9min 2s

In [72]:
# Add the mandatory category column
mandatory = ['work' , 'univ', 'school']
sf_stacked_rh_flsz['mandatoryCat'] = np.where((sf_stacked_rh_flsz.actEndType.isin(mandatory)) & (sf_stacked_rh_flsz.actStartType.isin(mandatory)), 'from_M_to_M' , None)

In [73]:
sf_stacked_rh_flsz['mandatoryCat'] = np.where((sf_stacked_rh_flsz.actEndType == 'Home') & (sf_stacked_rh_flsz.actStartType.isin(mandatory)), 'from_H_to_M' , sf_stacked_rh_flsz['mandatoryCat'])

In [74]:
sf_stacked_rh_flsz['mandatoryCat'] = np.where((sf_stacked_rh_flsz.actEndType.isin(mandatory)) & (sf_stacked_rh_flsz.actStartType == "Home"), 'from_M_to_H' , sf_stacked_rh_flsz['mandatoryCat'])

In [75]:
non_mandatory = ['othmaint' , 'othdiscr', 'escort', 'eatout', 'social', 'shopping', 'atwork']
sf_stacked_rh_flsz['mandatoryCat'] = np.where((sf_stacked_rh_flsz.actEndType.isin(non_mandatory)) & (sf_stacked_rh_flsz.actStartType.isin(non_mandatory)), 'from_N_to_N' , sf_stacked_rh_flsz['mandatoryCat'])

In [76]:
# shift columns to first position
first_column = sf_stacked_rh_flsz.pop('mandatoryCat')
# insert column using insert(position,column_name,first_column) function
sf_stacked_rh_flsz.insert(11, 'mandatoryCat', first_column)

In [77]:
# Drop unused columns
sf_stacked_rh_flsz = sf_stacked_rh_flsz.drop(['num_work_tours','num_joint_tours', 'non_mandatory_tour_frequency',
                                          'num_non_mand','num_escort_tours','num_eatout_tours','num_shop_tours',
                                          'num_maint_tours','num_discr_tours','num_social_tours','num_non_escort_tours'], axis=1)

In [79]:
sf_stacked_rh_flsz.head()

,IDMerged,tripIndex,scenario,lever,lever_position,logsum_relative_to_baseline,door_to_door_time_relative_to_baseline,income,actPurpose,logsum_trip_mode_AS_trips,mode_choice_actual_BEAM,mandatoryCat,actEndTime,actEndType,actStartTime,actStartType,cost_BEAM,distance_bike,distance_mode_choice,distance_privateCar,distance_ridehail,distance_transit,distance_travelling,distance_walking,duration_in_privateCar,duration_in_ridehail,duration_in_transit,duration_on_bike,duration_travelling,duration_walking,emissionBiodiesel,emissionDiesel,emissionElectricity,emissionFood,emissionGasoline,emission_marginal,fuelBiodiesel,fuelDiesel,fuelElectricity,fuelFood,fuelGasoline,fuel_marginal,fuel_not_Food,mode_choice_planned_BEAM,numPassengers,parkingType,reason,replanning_status,ride_hail_pooled,transit_bus,transit_cable_car,transit_rail,transit_subway,transit_tram,vehicleIds,year,duration_door_to_door,waitTime,mode_choice_actual_5,trip_id,person_id,household_id,tour_id,primary_purpose_x,trip_count,purpose,trip_mode_AS_trips,tour_type,tour_category,start,end,duration,tour_mode_AS_tours,earning,person_sex,sex,edu,race,work_at_home,age,value_of_time,free_parking_at_work,num_mand,lcm_county_id,tenure_mover,hh_size,tenure,hh_cars,hh_income,hhsize,income_in_thousands,median_value_of_time,hh_value_of_time,home_is_urban,home_is_rural,auto_ownership,AGEP,SEX,DIS,VEH,DRIVEALONEFREE,DRIVEALONEPAY,SHARED2FREE,SHARED2PAY,SHARED3FREE,SHARED3PAY,WALK,BIKE,WALK_LOC,WALK_LRF,WALK_EXP,WALK_HVY,WALK_COM,DRIVE_LOC,DRIVE_LRF,DRIVE_EXP,DRIVE_HVY,DRIVE_COM,TAXI,TNC_SINGLE,TNC_SHARED,mode_choice_actual_6
0,1,577.000000,ridehail,fleet_size,0.250000,0.253825,813.000000,240000.000000,Home_to_othmaint,-1.896507,hov3_teleportation,None,29073.000000,Home,30450.000000,othmaint,0.000000,0.000000,16246.598000,16246.598000,0.000000,0.000000,16246.598000,0.000000,1377.000000,0.000000,0.000000,0.000000,1377.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,1377.000000,0.000000,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.866180,car
1,1,577.000000,baseline,default,1.000000,0.000000,0.000000,240000.000000,Home_to_othmaint,-2.150332,hov3_teleportation,None,29037.000000,Home,29601.000000,othmaint,0.000000,0.000000,6498.758000,6498.758000,0.000000,0.000000,6498.758000,0.000000,564.000000,0.000000,0.000000,0.000000,564.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,564.000000,0.000000,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,SHARED2FREE,school,mandatory,8.000000,14.000000,6.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.828240,car
2,1,577.000000,ridehail,fleet_size,1.750000,1.167693,813.000000,240000.000000,Home_to_othmaint,-0.982639,hov3_teleportation,None,29350.000000,Home,30727.000000,othmaint,0.000000,0.000000,16246.598000,16246.598000,0.000000,0.000000,16246.598000,0.000000,1377.000000,0.000000,0.000000,0.000000,1377.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,1377.000000,0.000000,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,SHARED3PAY,school,mandatory,8.000000,14.000000,6.000000,SHARED3PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.445180,-999.446910,-3.185499,-3.186488,-2.216447,-2.217139,-2.388872,-999.925880,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-9.585779,-9.730563,-8.534333,car
3,1,578.000000,ridehail,fleet_size,0.250000,0.615956,813.000000,240000.000000,othmaint_to_school,-1.404211,hov3_teleportation,None,31179.000000,othmaint,32131.000000,school,0.000000,0.000000,11389.821000,11389.821000,0.000000,0.000000,11389.821000,0.000000,952.000000,0.000000,0.000000,0.000000,952.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,952.000000,0.000000,car,578.000000,1.000000,1735309.000000,72.000000,school,2.000000,school,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.203047,-999.203839,-2.943366,-2.943819,-1.974314,-1.974631,-1.962304,-999.712596,-1998.779651,-1998.779651,-1999.050651,-1998.779651,-1998.779651,-1999.528158,-2997.418679,-2998.777234,-2997.418679,-2997.418679,-9.202695,-9.493403,-8.148759,car
4,1,578.000000,baseline,default,1.000000,0.000000,0.000000,240000.000000,othmaint_to_school,-2.020166,hov3_teleportation,None,29751.000000,othmaint,29890.000000,school,0.000000,0.000000,1641.981000,1641.981000,0.000000,0.000000,1641.981000,0.000000,139.000000,0.000000,0.000000,0.000000,139.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,139.000000,0.000000,car,578.000000,1.000000,1735309.000000,72.000000,school,2.000000,school,SHARED2FREE,school,mandatory,8.000000,14.000000,6.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1998.779651,-1998.779651,-1999.050651,-1998.779651,-1998.779651,-1999.528158,-2997.418679,-2998.777234,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.958320,car

In [6]:
sf_stacked_tr_fr.mode_choice_actual_BEAM.unique()

array(['hov3_teleportation', 'car', 'walk_transit', 'ride_hail', 'walk',
       'car_hov2', 'hov2_teleportation', 'bike', 'car_hov3',
       'ride_hail_transit', 'drive_transit', 'ride_hail_pooled',
       'bike_transit'], dtype=object)

In [5]:
sf_stacked_tr_fr.trip_mode_AS_trips.unique()

array(['SHARED3FREE', 'SHARED2FREE', 'DRIVEALONEFREE', 'DRIVEALONEPAY',
       nan, 'SHARED2PAY', 'SHARED3PAY', 'WALK', 'BIKE', 'WALK_LOC',
       'WALK_HVY', 'WALK_EXP', 'WALK_LRF', 'TNC_SINGLE', 'TNC_SHARED',
       'TAXI', 'WALK_COM', 'DRIVE_EXP', 'DRIVE_HVY', 'DRIVE_LOC',
       'DRIVE_LRF', 'DRIVE_COM'], dtype=object)

In [19]:
# Rename to Potential INEXUS
sf_stacked_tr_fr.rename(columns={"logsum_trip_potential_INEXUS":"logsum_trip_Potential_INEXUS"}, inplace=True)

In [80]:
# Mapping BEAM and ASIM modes
conditions  = [(sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk'), 
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'bike'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED3FREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED3PAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED3FREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED3PAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED2FREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED2PAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED2PAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED2FREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVEALONEFREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVEALONEPAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LRF'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LOC'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_EXP'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_HVY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SINGLE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SHARED'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_pooled')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SINGLE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TAXI'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_COM'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_COM'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LRF'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LOC'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_EXP'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_HVY')]

choices = [sf_stacked_rh_flsz['WALK'], sf_stacked_rh_flsz['BIKE'], sf_stacked_rh_flsz['SHARED3FREE'], sf_stacked_rh_flsz['SHARED3PAY'],
           sf_stacked_rh_flsz['SHARED3FREE'], sf_stacked_rh_flsz['SHARED3PAY'], sf_stacked_rh_flsz['SHARED2FREE'], 
           sf_stacked_rh_flsz['SHARED2PAY'], sf_stacked_rh_flsz['SHARED2PAY'], sf_stacked_rh_flsz['SHARED2FREE'], 
           sf_stacked_rh_flsz['DRIVEALONEFREE'], sf_stacked_rh_flsz['DRIVEALONEPAY'], sf_stacked_rh_flsz['WALK_LRF'], 
           sf_stacked_rh_flsz['WALK_LOC'], sf_stacked_rh_flsz['WALK_EXP'], sf_stacked_rh_flsz['WALK_HVY'], sf_stacked_rh_flsz['TNC_SINGLE'], 
           sf_stacked_rh_flsz['TNC_SHARED'], sf_stacked_rh_flsz['TNC_SINGLE'], sf_stacked_rh_flsz['TAXI'], sf_stacked_rh_flsz['WALK_COM'], 
           sf_stacked_rh_flsz['DRIVE_COM'], sf_stacked_rh_flsz['DRIVE_LRF'], sf_stacked_rh_flsz['DRIVE_LOC'], sf_stacked_rh_flsz['DRIVE_EXP'],
           sf_stacked_rh_flsz['DRIVE_HVY']]

In [81]:
sf_stacked_rh_flsz['Realized_INEXUS'] = np.select(conditions, choices, default=np.nan)

In [82]:
# shift columns to first position
first_column = sf_stacked_rh_flsz.pop('Realized_INEXUS')
# insert column using insert(position,column_name,first_column) function
sf_stacked_rh_flsz.insert(5, 'Realized_INEXUS', first_column)

In [83]:
sf_stacked_rh_flsz.head()

,IDMerged,tripIndex,scenario,lever,lever_position,Realized_INEXUS,logsum_relative_to_baseline,door_to_door_time_relative_to_baseline,income,actPurpose,logsum_trip_mode_AS_trips,mode_choice_actual_BEAM,mandatoryCat,actEndTime,actEndType,actStartTime,actStartType,cost_BEAM,distance_bike,distance_mode_choice,distance_privateCar,distance_ridehail,distance_transit,distance_travelling,distance_walking,duration_in_privateCar,duration_in_ridehail,duration_in_transit,duration_on_bike,duration_travelling,duration_walking,emissionBiodiesel,emissionDiesel,emissionElectricity,emissionFood,emissionGasoline,emission_marginal,fuelBiodiesel,fuelDiesel,fuelElectricity,fuelFood,fuelGasoline,fuel_marginal,fuel_not_Food,mode_choice_planned_BEAM,numPassengers,parkingType,reason,replanning_status,ride_hail_pooled,transit_bus,transit_cable_car,transit_rail,transit_subway,transit_tram,vehicleIds,year,duration_door_to_door,waitTime,mode_choice_actual_5,trip_id,person_id,household_id,tour_id,primary_purpose_x,trip_count,purpose,trip_mode_AS_trips,tour_type,tour_category,start,end,duration,tour_mode_AS_tours,earning,person_sex,sex,edu,race,work_at_home,age,value_of_time,free_parking_at_work,num_mand,lcm_county_id,tenure_mover,hh_size,tenure,hh_cars,hh_income,hhsize,income_in_thousands,median_value_of_time,hh_value_of_time,home_is_urban,home_is_rural,auto_ownership,AGEP,SEX,DIS,VEH,DRIVEALONEFREE,DRIVEALONEPAY,SHARED2FREE,SHARED2PAY,SHARED3FREE,SHARED3PAY,WALK,BIKE,WALK_LOC,WALK_LRF,WALK_EXP,WALK_HVY,WALK_COM,DRIVE_LOC,DRIVE_LRF,DRIVE_EXP,DRIVE_HVY,DRIVE_COM,TAXI,TNC_SINGLE,TNC_SHARED,mode_choice_actual_6
0,1,577.000000,ridehail,fleet_size,0.250000,NaN,0.253825,813.000000,240000.000000,Home_to_othmaint,-1.896507,hov3_teleportation,None,29073.000000,Home,30450.000000,othmaint,0.000000,0.000000,16246.598000,16246.598000,0.000000,0.000000,16246.598000,0.000000,1377.000000,0.000000,0.000000,0.000000,1377.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,1377.000000,0.000000,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.866180,car
1,1,577.000000,baseline,default,1.000000,NaN,0.000000,0.000000,240000.000000,Home_to_othmaint,-2.150332,hov3_teleportation,None,29037.000000,Home,29601.000000,othmaint,0.000000,0.000000,6498.758000,6498.758000,0.000000,0.000000,6498.758000,0.000000,564.000000,0.000000,0.000000,0.000000,564.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,564.000000,0.000000,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,SHARED2FREE,school,mandatory,8.000000,14.000000,6.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.828240,car
2,1,577.000000,ridehail,fleet_size,1.750000,-2.217139,1.167693,813.000000,240000.000000,Home_to_othmaint,-0.982639,hov3_teleportation,None,29350.000000,Home,30727.000000,othmaint,0.000000,0.000000,16246.598000,16246.598000,0.000000,0.000000,16246.598000,0.000000,1377.000000,0.000000,0.000000,0.000000,1377.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,1377.000000,0.000000,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,SHARED3PAY,school,mandatory,8.000000,14.000000,6.000000,SHARED3PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.445180,-999.446910,-3.185499,-3.186488,-2.216447,-2.217139,-2.388872,-999.925880,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-9.585779,-9.730563,-8.534333,car
3,1,578.000000,ridehail,fleet_size,0.250000,NaN,0.615956,813.000000,240000.000000,othmaint_to_school,-1.404211,hov3_teleportation,None,31179.000000,othmaint,32131.000000,school,0.000000,0.000000,11389.821000,11389.821000,0.000000,0.000000,11389.821000,0.000000,952.000000,0.000000,0.000000,0.000000,952.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,952.000000,0.000000,car,578.000000,1.000000,1735309.000000,72.000000,school,2.000000,school,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.203047,-999.203839,-2.943366,-2.943819,-1.974314,-1.974631,-1.962304,-999.712596,-1998.779651,-1998.779651,-1999.050651,-1998.779651,-1998.779651,-1999.528158,-2997.418679,-2998.777234,-2997.418679,-2997.418679,-9.202695,-9.493403,-8.148759,car
4,1,578.000000,baseline,default,1.000000,NaN,0.000000,0.000000,240000.000000,othmaint_to_school,-2.020166,hov3_teleportation,None,29751.000000,othmaint,29890.000000,school,0.000000,0.000000,1641.981000,1641.981000,0.000000,0.000000,1641.981000,0.000000,139.000000,0.000000,0.000000,0.000000,139.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,139.000000,0.000000,car,578.000000,1.000000,1735309.000000,72.000000,school,2.000000,school,SHARED2FREE,school,mandatory,8.000000,14.000000,6.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1998.779651,-1998.779651,-1999.050651,-1998.779651,-1998.779651,-1999.528158,-2997.418679,-2998.777234,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.958320,car

In [29]:
sf_stacked_tr_fr[sf_stacked_tr_fr['Realized_INEXUS'].isna()].shape

(3489437, 123)

In [27]:
sf_stacked_tr_fr[sf_stacked_tr_fr['Realized_INEXUS'].isna()].head(10000).to_csv('C:/Shared-Work/Data/CleanData/ASIM_BEAM_Merged/realizedIN_empty.csv', index = False)

In [28]:
sf_stacked_tr_fr.shape

(10156414, 123)

In [51]:
%%time
sf_stacked_tr_fr.to_csv('s3://beam-core-act/deepDive/CleanData/SanFrancisco/Stacked/sf_2018_stacked_tr_fr_v3.csv', index=False)

CPU times: total: 11min 41s
Wall time: 15min 23s

#### Stacked v3

In [22]:
%%time
stacked_tr_fr_path = "https://beam-core-act.s3.amazonaws.com/deepDive/CleanData/SanFrancisco/Stacked/"
sf_stacked_tr_fr = pd.read_csv(stacked_tr_fr_path + 'sf_2018_stacked_tr_fr_v3.csv')

CPU times: total: 5min 41s
Wall time: 9min 16s

In [85]:
sf_stacked_rh_flsz = sf_stacked_rh_flsz[sf_stacked_rh_flsz['trip_mode_AS_trips'].notna()]

In [91]:
sf_stacked_rh_flsz = sf_stacked_rh_flsz.drop(['Realized_INEXUS'], axis=1)

In [92]:
# Mapping BEAM and ASIM modes
conditions  = [(sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk'), 
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'bike'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED3FREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED3PAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED3FREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED3PAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED2FREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED2PAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED2PAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED2FREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVEALONEFREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVEALONEPAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LRF'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LOC'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_EXP'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_HVY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SINGLE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SHARED'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TAXI'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_COM'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_COM'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LRF'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LOC'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_EXP'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'drive_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_HVY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED2FREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED2PAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED3PAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED3FREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED3PAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED2FREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED2PAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED3FREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED3PAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED3FREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVEALONEPAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov2')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVEALONEFREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVEALONEFREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVEALONEPAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED2FREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVEALONEPAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov3')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVEALONEFREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVEALONEFREE'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVEALONEPAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'SHARED2PAY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_pooled')&(sf_stacked_rh_flsz['ride_hail_pooled'] > 1),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov3_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov2_teleportation')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov2')&((sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_HVY')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_COM')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_EXP')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_COM')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_EXP')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_HVY')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LOC')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LRF')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LRF')| 
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LOC')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'BIKE')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SINGLE')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SHARED')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TAXI'))
                    & (sf_stacked_rh_flsz['cost_BEAM'] > 2.5),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov3')&((sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_HVY')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_COM')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_EXP')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_COM')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_EXP')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_HVY')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LOC')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LRF')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LRF')| 
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LOC')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'BIKE')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SINGLE')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SHARED')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TAXI'))
                    & (sf_stacked_rh_flsz['cost_BEAM'] > 2.5),
              (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov2')&((sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_HVY')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_COM')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_EXP')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_COM')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_EXP')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_HVY')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LOC')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LRF')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LRF')| 
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LOC')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'BIKE')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SINGLE')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SHARED')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TAXI'))
                    & (sf_stacked_rh_flsz['cost_BEAM'] <= 2.5),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car_hov3')&((sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_HVY')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_COM')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_EXP')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_COM')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_EXP')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_HVY')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LOC')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LRF')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LRF')| 
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LOC')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'BIKE')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SINGLE')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SHARED')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TAXI'))
                    & (sf_stacked_rh_flsz['cost_BEAM'] <= 2.5),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car')&((sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_HVY')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_COM')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_EXP')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_COM')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_EXP')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_HVY')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LOC')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LRF')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LRF')| 
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LOC')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'BIKE')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SINGLE')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SHARED')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TAXI'))
                    & (sf_stacked_rh_flsz['cost_BEAM'] <= 2.5),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'car')&((sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_HVY')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_COM')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_EXP')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_COM')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_EXP')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_HVY')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LOC')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LRF')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LRF')| 
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LOC')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'BIKE')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SINGLE')|
                    (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TNC_SHARED')|(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'TAXI'))
                    & (sf_stacked_rh_flsz['cost_BEAM'] > 2.5),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_pooled'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_COM'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LRF'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_LOC'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_EXP'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'DRIVE_HVY'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_COM'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LRF'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_LOC'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_EXP'),
               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail_transit')&(sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'WALK_HVY')]
        
choices = [sf_stacked_rh_flsz['WALK'], sf_stacked_rh_flsz['BIKE'], sf_stacked_rh_flsz['SHARED3FREE'], sf_stacked_rh_flsz['SHARED3PAY'],
           sf_stacked_rh_flsz['SHARED3FREE'], sf_stacked_rh_flsz['SHARED3PAY'], sf_stacked_rh_flsz['SHARED2FREE'], 
           sf_stacked_rh_flsz['SHARED2PAY'], sf_stacked_rh_flsz['SHARED2PAY'], sf_stacked_rh_flsz['SHARED2FREE'], 
           sf_stacked_rh_flsz['DRIVEALONEFREE'], sf_stacked_rh_flsz['DRIVEALONEPAY'], sf_stacked_rh_flsz['WALK_LRF'], 
           sf_stacked_rh_flsz['WALK_LOC'], sf_stacked_rh_flsz['WALK_EXP'], sf_stacked_rh_flsz['WALK_HVY'], sf_stacked_rh_flsz['TNC_SINGLE'], 
           sf_stacked_rh_flsz['TNC_SHARED'], sf_stacked_rh_flsz['TAXI'], sf_stacked_rh_flsz['WALK_COM'], 
           sf_stacked_rh_flsz['DRIVE_COM'], sf_stacked_rh_flsz['DRIVE_LRF'], sf_stacked_rh_flsz['DRIVE_LOC'], sf_stacked_rh_flsz['DRIVE_EXP'],
           sf_stacked_rh_flsz['DRIVE_HVY'], sf_stacked_rh_flsz['SHARED3FREE'], sf_stacked_rh_flsz['DRIVEALONEPAY'], sf_stacked_rh_flsz['DRIVEALONEPAY'],
           sf_stacked_rh_flsz['SHARED2FREE'], sf_stacked_rh_flsz['SHARED2PAY'], sf_stacked_rh_flsz['SHARED3FREE'],  sf_stacked_rh_flsz['SHARED3PAY'],
           sf_stacked_rh_flsz['SHARED2FREE'], sf_stacked_rh_flsz['SHARED2PAY'], sf_stacked_rh_flsz['DRIVEALONEFREE'], sf_stacked_rh_flsz['SHARED2PAY'], 
           sf_stacked_rh_flsz['SHARED2FREE'], sf_stacked_rh_flsz['SHARED2FREE'], sf_stacked_rh_flsz['SHARED2PAY'], sf_stacked_rh_flsz['DRIVEALONEFREE'], 
           sf_stacked_rh_flsz['SHARED3PAY'], sf_stacked_rh_flsz['SHARED3FREE'], sf_stacked_rh_flsz['SHARED3FREE'], sf_stacked_rh_flsz['SHARED3PAY'],
           sf_stacked_rh_flsz['SHARED3PAY'], sf_stacked_rh_flsz['TNC_SHARED'], sf_stacked_rh_flsz['SHARED3FREE'], sf_stacked_rh_flsz['SHARED2FREE'],
           sf_stacked_rh_flsz['SHARED2PAY'], sf_stacked_rh_flsz['SHARED3PAY'], sf_stacked_rh_flsz['SHARED2FREE'],sf_stacked_rh_flsz['SHARED3FREE'],
           sf_stacked_rh_flsz['DRIVEALONEFREE'], sf_stacked_rh_flsz['DRIVEALONEPAY'], sf_stacked_rh_flsz['TNC_SHARED'], sf_stacked_rh_flsz['DRIVE_COM'],
           sf_stacked_rh_flsz['DRIVE_LRF'], sf_stacked_rh_flsz['DRIVE_LOC'], sf_stacked_rh_flsz['DRIVE_EXP'], sf_stacked_rh_flsz['DRIVE_HVY'],
           sf_stacked_rh_flsz['WALK_COM'], sf_stacked_rh_flsz['WALK_LRF'], sf_stacked_rh_flsz['WALK_LOC'], sf_stacked_rh_flsz['WALK_EXP'],
           sf_stacked_rh_flsz['WALK_HVY']]

In [93]:
sf_stacked_rh_flsz['Realized_INEXUS'] = np.select(conditions, choices, default=np.nan)

In [94]:
# shift columns to first position
first_column = sf_stacked_rh_flsz.pop('Realized_INEXUS')
# insert column using insert(position,column_name,first_column) function
sf_stacked_rh_flsz.insert(5, 'Realized_INEXUS', first_column)

In [95]:
sf_stacked_rh_flsz['Realized_INEXUS'] = np.where((sf_stacked_rh_flsz['Realized_INEXUS'].isna())&
                                               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail')&
                                               ((sf_stacked_rh_flsz['numPassengers'] == '1.0, 1.0, 1.0')|
                                                (sf_stacked_rh_flsz['numPassengers'] =='1.0, 1.0, 1.0, 1.0')|
                                                (sf_stacked_rh_flsz['numPassengers'] =='1.0, 1.0, 1.0, 1.0, 1.0')|
                                                (sf_stacked_rh_flsz['numPassengers'] =='1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0')|
                                                (sf_stacked_rh_flsz['numPassengers'] =='1.0, 8.0, 8.0, 7.0, 1.0, 1.0, 1.0, 1.0')|
                                                (sf_stacked_rh_flsz['numPassengers'] =='1.0, 16.0, 1.0, 1.0, 1.0, 1.0')|
                                                (sf_stacked_rh_flsz['numPassengers'] =='1.0, 10.0, 11.0, 1.0, 1.0, 1.0, 1.0')), 
                                                sf_stacked_rh_flsz['TNC_SINGLE'], sf_stacked_rh_flsz['Realized_INEXUS'])

In [96]:
sf_stacked_rh_flsz['Realized_INEXUS'] = np.where((sf_stacked_rh_flsz['Realized_INEXUS'].isna())&
                                               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov2_teleportation'), 
                                                sf_stacked_rh_flsz.loc[:, ["SHARED2FREE", "SHARED2PAY"]].max(1), sf_stacked_rh_flsz['Realized_INEXUS'])

In [97]:
sf_stacked_rh_flsz['Realized_INEXUS'] = np.where((sf_stacked_rh_flsz['Realized_INEXUS'].isna())&
                                               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'hov3_teleportation'), 
                                                sf_stacked_rh_flsz.loc[:, ["SHARED3FREE", "SHARED3PAY"]].max(1), sf_stacked_rh_flsz['Realized_INEXUS'])

In [98]:
sf_stacked_rh_flsz['Realized_INEXUS'] = np.where((sf_stacked_rh_flsz['Realized_INEXUS'].isna())&
                                               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'walk_transit'), 
                                                sf_stacked_rh_flsz.loc[:, ["WALK_COM", "WALK_LRF", "WALK_LOC", "WALK_EXP",
                                                      "WALK_HVY"]].max(1), sf_stacked_rh_flsz['Realized_INEXUS'])

In [99]:
sf_stacked_rh_flsz['Realized_INEXUS'] = np.where((sf_stacked_rh_flsz['Realized_INEXUS'].isna())&
                                               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'drive_transit'), 
                                                sf_stacked_rh_flsz.loc[:, ["DRIVE_COM", "DRIVE_LRF", "DRIVE_LOC", "DRIVE_EXP",
                                                      "DRIVE_HVY"]].max(1), sf_stacked_rh_flsz['Realized_INEXUS'])

In [100]:
sf_stacked_rh_flsz['Realized_INEXUS'] = np.where((sf_stacked_rh_flsz['Realized_INEXUS'].isna())&
                                               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'bike_transit')&
                                               (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'BIKE'), 
                                                sf_stacked_rh_flsz['BIKE'], sf_stacked_rh_flsz['Realized_INEXUS'])

In [101]:
sf_stacked_rh_flsz['Realized_INEXUS'] = np.where((sf_stacked_rh_flsz['Realized_INEXUS'].isna())&
                                               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'bike_transit')&
                                               (sf_stacked_rh_flsz['trip_mode_AS_trips'] == 'BIKE'), 
                                                sf_stacked_rh_flsz['BIKE'], sf_stacked_rh_flsz['Realized_INEXUS'])

In [102]:
sf_stacked_rh_flsz['Realized_INEXUS'] = np.where((sf_stacked_rh_flsz['Realized_INEXUS'].isna())&
                                               (sf_stacked_rh_flsz['mode_choice_actual_BEAM'] == 'ride_hail'), 
                                                sf_stacked_rh_flsz['TNC_SINGLE'], sf_stacked_rh_flsz['Realized_INEXUS'])

In [103]:
sf_stacked_rh_flsz[sf_stacked_rh_flsz['Realized_INEXUS'].isna()].shape

(1084, 123)

In [ ]:
#sf_stacked_tr_fr['Realized_INEXUS'] = np.where((sf_stacked_tr_fr['Realized_INEXUS'].isna())&
                                               #(sf_stacked_tr_fr['mode_choice_actual_BEAM'] == 'walk_transit')&
                                               #(sf_stacked_tr_fr['vehicleIds'].str.contains('(caltrain)')), 
                                               #sf_stacked_tr_fr['WALK_COM'], sf_stacked_tr_fr['Realized_INEXUS'])

In [104]:
sf_stacked_rh_flsz = sf_stacked_rh_flsz[sf_stacked_rh_flsz['Realized_INEXUS'].notna()]

In [19]:
#sf_stacked_tr_fr[sf_stacked_tr_fr['Realized_INEXUS'].isna()].to_csv('C:/Shared-Work/Data/CleanData/ASIM_BEAM_Merged/realizedIN_empty.csv', index = False)

In [38]:
%%time
sf_stacked_tr_fr.to_csv('s3://beam-core-act/deepDive/CleanData/SanFrancisco/Stacked/sf_2018_stacked_tr_fr_v4.csv', index=False)

CPU times: total: 13min 51s
Wall time: 17min 20s

#### Stacked v4

In [3]:
%%time
stacked_tr_fr_path = "https://beam-core-act.s3.amazonaws.com/deepDive/CleanData/SanFrancisco/Stacked/"
sf_stacked_tr_fr = pd.read_csv(stacked_tr_fr_path + 'sf_2018_stacked_tr_fr_v4.csv')

CPU times: total: 2min 25s
Wall time: 6min 39s

#### Social INEXUS

In [105]:
sf_stacked_rh_flsz.income.quantile([0, 0.25,0.5,0.75, 1.00])

0.000000    -14600.000000
0.250000     49800.000000
0.500000     93400.000000
0.750000    155000.000000
1.000000   1354000.000000
Name: income, dtype: float64

In [106]:
# determine the quartile values to use with pd.cut
quartiles = sf_stacked_rh_flsz['income'].quantile([.25, .5, .75]).tolist()

In [107]:
# add a lower and upper range for the bins in pd.cut
quartiles = [0] + quartiles + [float('inf')]

In [108]:
# add a quartiles column to groups, using pd.cut
sf_stacked_rh_flsz['income_quartiles'] = pd.cut(sf_stacked_rh_flsz['income'], bins=quartiles, labels=['1stQ', '2ndQ', '3rdQ', '4thQ'])

In [109]:
sf_stacked_rh_flsz.head()

,IDMerged,tripIndex,scenario,lever,lever_position,Realized_INEXUS,logsum_relative_to_baseline,door_to_door_time_relative_to_baseline,income,actPurpose,logsum_trip_mode_AS_trips,mode_choice_actual_BEAM,mandatoryCat,actEndTime,actEndType,actStartTime,actStartType,cost_BEAM,distance_bike,distance_mode_choice,distance_privateCar,distance_ridehail,distance_transit,distance_travelling,distance_walking,duration_in_privateCar,duration_in_ridehail,duration_in_transit,duration_on_bike,duration_travelling,duration_walking,emissionBiodiesel,emissionDiesel,emissionElectricity,emissionFood,emissionGasoline,emission_marginal,fuelBiodiesel,fuelDiesel,fuelElectricity,fuelFood,fuelGasoline,fuel_marginal,fuel_not_Food,mode_choice_planned_BEAM,numPassengers,parkingType,reason,replanning_status,ride_hail_pooled,transit_bus,transit_cable_car,transit_rail,transit_subway,transit_tram,vehicleIds,year,duration_door_to_door,waitTime,mode_choice_actual_5,trip_id,person_id,household_id,tour_id,primary_purpose_x,trip_count,purpose,trip_mode_AS_trips,tour_type,tour_category,start,end,duration,tour_mode_AS_tours,earning,person_sex,sex,edu,race,work_at_home,age,value_of_time,free_parking_at_work,num_mand,lcm_county_id,tenure_mover,hh_size,tenure,hh_cars,hh_income,hhsize,income_in_thousands,median_value_of_time,hh_value_of_time,home_is_urban,home_is_rural,auto_ownership,AGEP,SEX,DIS,VEH,DRIVEALONEFREE,DRIVEALONEPAY,SHARED2FREE,SHARED2PAY,SHARED3FREE,SHARED3PAY,WALK,BIKE,WALK_LOC,WALK_LRF,WALK_EXP,WALK_HVY,WALK_COM,DRIVE_LOC,DRIVE_LRF,DRIVE_EXP,DRIVE_HVY,DRIVE_COM,TAXI,TNC_SINGLE,TNC_SHARED,mode_choice_actual_6,income_quartiles
0,1,577.000000,ridehail,fleet_size,0.250000,-1.796358,0.253825,813.000000,240000.000000,Home_to_othmaint,-1.896507,hov3_teleportation,None,29073.000000,Home,30450.000000,othmaint,0.000000,0.000000,16246.598000,16246.598000,0.000000,0.000000,16246.598000,0.000000,1377.000000,0.000000,0.000000,0.000000,1377.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,1377.000000,0.000000,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.866180,car,4thQ
1,1,577.000000,baseline,default,1.000000,-1.796358,0.000000,0.000000,240000.000000,Home_to_othmaint,-2.150332,hov3_teleportation,None,29037.000000,Home,29601.000000,othmaint,0.000000,0.000000,6498.758000,6498.758000,0.000000,0.000000,6498.758000,0.000000,564.000000,0.000000,0.000000,0.000000,564.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,564.000000,0.000000,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,SHARED2FREE,school,mandatory,8.000000,14.000000,6.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.828240,car,4thQ
2,1,577.000000,ridehail,fleet_size,1.750000,-2.217139,1.167693,813.000000,240000.000000,Home_to_othmaint,-0.982639,hov3_teleportation,None,29350.000000,Home,30727.000000,othmaint,0.000000,0.000000,16246.598000,16246.598000,0.000000,0.000000,16246.598000,0.000000,1377.000000,0.000000,0.000000,0.000000,1377.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,1377.000000,0.000000,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,SHARED3PAY,school,mandatory,8.000000,14.000000,6.000000,SHARED3PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.445180,-999.446910,-3.185499,-3.186488,-2.216447,-2.217139,-2.388872,-999.925880,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-9.585779,-9.730563,-8.534333,car,4thQ
3,1,578.000000,ridehail,fleet_size,0.250000,-1.974314,0.615956,813.000000,240000.000000,othmaint_to_school,-1.404211,hov3_teleportation,None,31179.000000,othmaint,32131.000000,school,0.000000,0.000000,11389.821000,11389.821000,0.000000,0.000000,11389.821000,0.000000,952.000000,0.000000,0.000000,0.000000,952.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,952.000000,0.000000,car,578.000000,1.000000,1735309.000000,72.000000,school,2.000000,school,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.203047,-999.203839,-2.943366,-2.943819,-1.974314,-1.974631,-1.962304,-999.712596,-1998.779651,-1998.779651,-1999.050651,-1998.779651,-1998.779651,-1999.528158,-2997.418679,-2998.777234,-2997.418679,-2997.418679,-9.202695,-9.493403,-8.148759,car,4thQ
4,1,578.000000,baseline,default,1.000000,-1.796358,0.000000,0.000000,240000.000000,othmaint_to_school,-2.020166,hov3_teleportation,None,29751.000000,othmaint,29890.000000,school,0.000000,0.000000,1641.981000,1641.981000,0.000000,0.000000,1641.981000,0.000000,139.000000,0.000000,0.000000,0.000000,139.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,139.000000,0.000000,car,578.000000,1.000000,1735309.000000,72.000000,school,2.000000,school,SHARED2FREE,school,mandatory,8.000000,14.000000,6.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1998.779651,-1998.779651,-1999.050651,-1998.779651,-1998.779651,-1999.528158,-2997.418679,-2998.777234,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.958320,car,4thQ

In [110]:
m = sf_stacked_rh_flsz.groupby(['income_quartiles'])['income'].median()

In [111]:
m

income_quartiles
1stQ    29300.000000
2ndQ    70000.000000
3rdQ   120000.000000
4thQ   219000.000000
Name: income, dtype: float64

In [112]:
# Mapping BEAM and ASIM modes
conditions  = [(sf_stacked_rh_flsz['income_quartiles'] == '1stQ'), 
               (sf_stacked_rh_flsz['income_quartiles'] == '2ndQ'),
               (sf_stacked_rh_flsz['income_quartiles'] == '3rdQ'),
               (sf_stacked_rh_flsz['income_quartiles'] == '4thQ')]

choices = [29300, 70000, 120000, 219000]

In [113]:
sf_stacked_rh_flsz['MedianQuartiles'] = np.select(conditions, choices, default=np.nan)

In [114]:
sf_stacked_rh_flsz['alpha'] = 0.1

In [116]:
sf_stacked_rh_flsz['socialCarbonCost'] = sf_stacked_rh_flsz['emission_marginal']*51 # or 102

In [117]:
sf_stacked_rh_flsz['Social_INEXUS'] = (sf_stacked_rh_flsz['Realized_INEXUS']/sf_stacked_rh_flsz['alpha']) - sf_stacked_rh_flsz['socialCarbonCost']

In [120]:
sf_stacked_rh_flsz['Potential_INEXUS_in_dollar'] = sf_stacked_rh_flsz['logsum_trip_mode_AS_trips']/sf_stacked_rh_flsz['alpha']

In [122]:
sf_stacked_rh_flsz['Realized_INEXUS_in_dollar'] = sf_stacked_rh_flsz['Realized_INEXUS']/sf_stacked_rh_flsz['alpha']

In [169]:
#sf_stacked_tr_fr[((sf_stacked_tr_fr['duration_travelling'] <= 600) | (sf_stacked_tr_fr['duration_travelling'] > 550)) & (sf_stacked_tr_fr['mode_choice_actual_BEAM']=='car')].head()

In [123]:
# shift columns to first position
first_column = sf_stacked_rh_flsz.pop('Social_INEXUS')
# insert column using insert(position,column_name,first_column) function
sf_stacked_rh_flsz.insert(6, 'Social_INEXUS', first_column)

In [124]:
# shift columns to first position
first_column = sf_stacked_rh_flsz.pop('Potential_INEXUS_in_dollar')
second_column = sf_stacked_rh_flsz.pop('Realized_INEXUS_in_dollar')
# insert column using insert(position,column_name,first_column) function
sf_stacked_rh_flsz.insert(7, 'Potential_INEXUS_in_dollar', first_column)
sf_stacked_rh_flsz.insert(8, 'Realized_INEXUS_in_dollar', first_column)

In [126]:
sf_stacked_rh_flsz.head()

,IDMerged,tripIndex,scenario,lever,lever_position,Realized_INEXUS,Social_INEXUS,Potential_INEXUS_in_dollar,Realized_INEXUS_in_dollar,logsum_relative_to_baseline,door_to_door_time_relative_to_baseline,income,actPurpose,logsum_trip_mode_AS_trips,mode_choice_actual_BEAM,mandatoryCat,actEndTime,actEndType,actStartTime,actStartType,cost_BEAM,distance_bike,distance_mode_choice,distance_privateCar,distance_ridehail,distance_transit,distance_travelling,distance_walking,duration_in_privateCar,duration_in_ridehail,duration_in_transit,duration_on_bike,duration_travelling,duration_walking,emissionBiodiesel,emissionDiesel,emissionElectricity,emissionFood,emissionGasoline,emission_marginal,fuelBiodiesel,fuelDiesel,fuelElectricity,fuelFood,fuelGasoline,fuel_marginal,fuel_not_Food,mode_choice_planned_BEAM,numPassengers,parkingType,reason,replanning_status,ride_hail_pooled,transit_bus,transit_cable_car,transit_rail,transit_subway,transit_tram,vehicleIds,year,duration_door_to_door,waitTime,mode_choice_actual_5,trip_id,person_id,household_id,tour_id,primary_purpose_x,trip_count,purpose,trip_mode_AS_trips,tour_type,tour_category,start,end,duration,tour_mode_AS_tours,earning,person_sex,sex,edu,race,work_at_home,age,value_of_time,free_parking_at_work,num_mand,lcm_county_id,tenure_mover,hh_size,tenure,hh_cars,hh_income,hhsize,income_in_thousands,median_value_of_time,hh_value_of_time,home_is_urban,home_is_rural,auto_ownership,AGEP,SEX,DIS,VEH,DRIVEALONEFREE,DRIVEALONEPAY,SHARED2FREE,SHARED2PAY,SHARED3FREE,SHARED3PAY,WALK,BIKE,WALK_LOC,WALK_LRF,WALK_EXP,WALK_HVY,WALK_COM,DRIVE_LOC,DRIVE_LRF,DRIVE_EXP,DRIVE_HVY,DRIVE_COM,TAXI,TNC_SINGLE,TNC_SHARED,mode_choice_actual_6,income_quartiles,MedianQuartiles,alpha,socialCarbonCost
0,1,577.000000,ridehail,fleet_size,0.250000,-1.796358,-17.963577,-18.965072,-18.965072,0.253825,813.000000,240000.000000,Home_to_othmaint,-1.896507,hov3_teleportation,None,29073.000000,Home,30450.000000,othmaint,0.000000,0.000000,16246.598000,16246.598000,0.000000,0.000000,16246.598000,0.000000,1377.000000,0.000000,0.000000,0.000000,1377.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,1377.000000,0.000000,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.866180,car,4thQ,219000.000000,0.100000,0.000000
1,1,577.000000,baseline,default,1.000000,-1.796358,-17.963577,-21.503324,-21.503324,0.000000,0.000000,240000.000000,Home_to_othmaint,-2.150332,hov3_teleportation,None,29037.000000,Home,29601.000000,othmaint,0.000000,0.000000,6498.758000,6498.758000,0.000000,0.000000,6498.758000,0.000000,564.000000,0.000000,0.000000,0.000000,564.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,564.000000,0.000000,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,SHARED2FREE,school,mandatory,8.000000,14.000000,6.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.828240,car,4thQ,219000.000000,0.100000,0.000000
2,1,577.000000,ridehail,fleet_size,1.750000,-2.217139,-22.171393,-9.826392,-9.826392,1.167693,813.000000,240000.000000,Home_to_othmaint,-0.982639,hov3_teleportation,None,29350.000000,Home,30727.000000,othmaint,0.000000,0.000000,16246.598000,16246.598000,0.000000,0.000000,16246.598000,0.000000,1377.000000,0.000000,0.000000,0.000000,1377.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,1377.000000,0.000000,car,577.000000,1.000000,1735309.000000,72.000000,school,2.000000,othmaint,SHARED3PAY,school,mandatory,8.000000,14.000000,6.000000,SHARED3PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.445180,-999.446910,-3.185499,-3.186488,-2.216447,-2.217139,-2.388872,-999.925880,-1000.490635,-1998.779651,-1999.490635,-1998.779651,-1998.779651,-1998.976381,-2997.418679,-2998.052261,-2997.418679,-2997.418679,-9.585779,-9.730563,-8.534333,car,4thQ,219000.000000,0.100000,0.000000
3,1,578.000000,ridehail,fleet_size,0.250000,-1.974314,-19.743143,-14.042106,-14.042106,0.615956,813.000000,240000.000000,othmaint_to_school,-1.404211,hov3_teleportation,None,31179.000000,othmaint,32131.000000,school,0.000000,0.000000,11389.821000,11389.821000,0.000000,0.000000,11389.821000,0.000000,952.000000,0.000000,0.000000,0.000000,952.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,952.000000,0.000000,car,578.000000,1.000000,1735309.000000,72.000000,school,2.000000,school,SHARED2FREE,school,mandatory,8.000000,15.000000,7.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.203047,-999.203839,-2.943366,-2.943819,-1.974314,-1.974631,-1.962304,-999.712596,-1998.779651,-1998.779651,-1999.050651,-1998.779651,-1998.779651,-1999.528158,-2997.418679,-2998.777234,-2997.418679,-2997.418679,-9.202695,-9.493403,-8.148759,car,4thQ,219000.000000,0.100000,0.000000
4,1,578.000000,baseline,default,1.000000,-1.796358,-17.963577,-20.201664,-20.201664,0.000000,0.000000,240000.000000,othmaint_to_school,-2.020166,hov3_teleportation,None,29751.000000,othmaint,29890.000000,school,0.000000,0.000000,1641.981000,1641.981000,0.000000,0.000000,1641.981000,0.000000,139.000000,0.000000,0.000000,0.000000,139.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,hov3_teleportation,NaN,NaN,NaN,0,0,0,0,0,0,0,NaN,2018,139.000000,0.000000,car,578.000000,1.000000,1735309.000000,72.000000,school,2.000000,school,SHARED2FREE,school,mandatory,8.000000,14.000000,6.000000,SHARED2PAY,0.000000,male,1.000000,1.000000,asian,0.000000,3.000000,19.798008,False,1.000000,6085.000000,own not recent,four or more,1.000000,two or more,gt150,4.000000,240.000000,12.860000,29.682171,False,False,2.000000,3.000000,1.000000,2.000000,2.000000,-999.025090,-999.025207,-2.765410,-2.765477,-1.796358,-1.796405,-1.962304,-999.712596,-1998.779651,-1998.779651,-1999.050651,-1998.779651,-1998.779651,-1999.528158,-2997.418679,-2998.777234,-2997.418679,-2997.418679,-8.970132,-9.314771,-7.958320,car,4thQ,219000.000000,0.100000,0.000000

In [127]:
%%time
sf_stacked_rh_flsz.to_csv('s3://beam-core-act/deepDive/CleanData/SanFrancisco/Stacked/sf_2018_stacked_rh_flsz.csv', index=False)

CPU times: total: 10min 17s
Wall time: 13min 24s